### ISSUE TITLE
Launch config on vscode

### ISSUE THREAD

**Issue by jchavarri** [jaredly/reason-language-server#1]
This looks very exciting! ✨ 

While trying to test it, i've followed the readme instructions, but got stuck in the point that says

> select "Debug > Start Without Debugging" from the vscode menu

It seems that `.vscode` [is part of `.gitignore`](https://github.com/jaredly/reason-language-server/blob/master/.gitignore#L7) so I'm not sure which launch config should apply? VSCode can't find it either.

Also, is the root folder that one that needs to be opened in vscode? Or [the `client` folder](https://github.com/jaredly/reason-language-server/tree/master/client)?

**Comment by jaredly** [comment]
haha oops, added those in. If you open the project folder in vscode, then it will have the correct task (not the client folder)
