### ISSUE TITLE
Infinite loop on save (`workspace/didChangeWatchedFiles` event)

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#100]
RLS goes into infinite loop and triggers `workspace/didChangeWatchedFiles` event after the very first save of a file. OLS works fine.

Editor: Atom
Demo: https://cl.ly/3x071R3i3G3n

**Comment by jaredly** [comment]
hmmmm ok I guess I need to track the previous content of bsconfig.json and .merlin files instead of just checking that mtime changed
