### ISSUE TITLE
JSX: no data is emitted for custom components

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#101]
`<MyComponent />`: when I try to get type data (on hover) or go to a module (Cmd + click)—nothing happens.

Editor: Atom
Demo: https://cl.ly/3h3i0A450E2D

On the demo:
1. I tried to get data on hover: no data were received.
2. I added invalid component: RLS gave me an error message and on Cmd + click took me to `ReasonReact` module.
3. When I fixed all errors: no data were received.

Log for hover event:

```
Reason (reason) rpc.sendRequest textDocument/hover sending 
{
  position: { character: 16, line: 270 },
  textDocument: { uri: "file:///..." },
}

Reason (reason) rpc.sendRequest textDocument/hover received (542ms)
```

**Comment by jaredly** [comment]
Annoyingly, the JSX transformation that refmt does doesn't preserve location data for the `MyComponent` identifier 😡 but I can hack around it

**Comment by jsiebern** [comment]
As this is kind of related: Most of the time when I `CMD+click` a custom JSX tag I get sent to the definition of ReasonReact rather than my component.

**Comment by jaredly** [comment]
yeahhh the jsx transform puts the location of `ReasonReact.element` covering the jsx tag

**Comment by MoOx** [comment]
It seems it's better now, at least when component props are filled without errors. As soon as you introduce an error, cmd+click will redirect to ReasonReact.
@jaredly would this be hard to make the situation better? Can you give me a pointer?

**Comment by alexfedoseev** [comment]
It seems like in JSX@3 this issue is gone. That's not 100% but so far all Cmd+clicks work as expected.

**Comment by jsiebern** [comment]
So far I can confirm @alexfedoseev message, doesn't seem to be an issue anymore.

**Comment by alexfedoseev** [comment]
Taking it back, still seeing this relatively often.

**Comment by jchavarri** [comment]
> but I can hack around it

@jaredly do you have some pointers or indications on how a solution would look like? I realized that in the plain Reason ppx (no React) right now the positions for the upper case modules work if the module name has the same length or more than `createElement` 😄 

Also, if it's smaller, rls sends negative numbers for start position, that vscode ignores if there is not enough space at the left of the identifier.

Here's a recording with the findings:

![react_ppx3](https://user-images.githubusercontent.com/220424/59474743-4a7ce780-8e48-11e9-9cde-fd78278d8d72.gif)

I was wondering if your solution involves "calculating back" the positions based on ids?
