### ISSUE TITLE
Support vendor modules

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#111]
When I cmd + click to some vendor module (e.g. `ReasonReact`, `Webapi` etc), toolchain doesn't work there. It would be great to be able to get type info & navigate there as well.

**Comment by splodingsocks** [comment]
This is a huge yes for me as well. I end up doing this all the time.

**Comment by jaredly** [comment]
I think this is fixed in the latest release 1.2.0 (at least navigating into ReasonReact works for me). lmk if it's not working for you.

**Comment by alexfedoseev** [comment]
ReasonReact & Webapi both work great, thanks!

**Comment by splodingsocks** [comment]
Its works to link into an external module, but it stops working within that external module, unfortunately. I find that I need to explore the source of libraries I'm using not infrequently, and it really helps to be able to "go to definition" inside of a vendor module. Would that be realistic to consider, @jaredly? Or would that hurt performance significantly?

**Comment by alexfedoseev** [comment]
@splodingsocks I can navigate inside mentioned libs, what’s the lib in wich you’re unable to navigate?
