### ISSUE TITLE
VSCode plugin installed on Windows doesn't work if you `npm install` the project from WSL

### ISSUE THREAD

**Issue by matthewsimo** [jaredly/reason-language-server#114]
Hello, I saw windows on ramp was easier now so I thought I'd give it a try but got this message at the top of a fresh basic-reason project. I'm running WSL on this PC. 

My steps:
- installed extension to VS Code.
- `npm install -g bs-platform`
- `bsb -init testing-reason -theme basic-reason`
- `code .`
- open `src/Demo.re` - wait a couple secs and see 'Unable to load compilation data: Could not run bsb' message

I see bsb there, so I'm not sure what's up. Assuming crossed wires or a PATH problem but not sure where to start.
```
$ bsb -where
/mnt/c/Users/msimo/.npm-global/lib/node_modules/bs-platform/lib
```

My `node_modules/.lsp/debug.log` - http://mas.im/e691fe3d26fb

Thanks for any guidance, appreciate any help.

**Comment by jaredly** [comment]
I'll try to get a WLS vm running to diagnose

**Comment by jaredly** [comment]
@matthewsimo could you update the extension to 1.0.3 and see if it's fixed?

**Comment by matthewsimo** [comment]
@jaredly Thanks for taking the time, appreciate it. Unfortunately, I updated and still see the same message. Here's the fresh `debug.log` - http://mas.im/418d4dfca048

I'll carve some time to try and dig in this weekend.

**Comment by jaredly** [comment]
I assume you've installed the windows vscode, but then you did `npm install` from wsl? Or did you install vscode within wsl?

**Comment by matthewsimo** [comment]
Yea, downloaded installer for Windows for VSCode and install
node/npm/bs-platform via WSL.

**Comment by stevelacy** [comment]
I am also getting this error on macos 10.14 Beta with vscode on the same example project as @matthewsimo

**Comment by jaredly** [comment]
@stevelacy hrmm I should really make that error message more informative. I wonder what macos 10.14 doesn't like

**Comment by phated** [comment]
@jaredly the only thing I could come up with that was different between @stevelacy's setup and mine was that he's using case-sensitive macos instead of case-insensitive. Would that have any effect?

**Comment by jaredly** [comment]
Oh that's interesting. I mean, linux is case sensitive and it works...

**Comment by WesleyvHaren** [comment]
I have the same error on my project on Windows as well, I installed bs-platform via WLS and the windows version of VSCode 

The testing-reason project gives the same error as well

I have been screwing around a lot to get the old OCaml and Reason plugin working, that one worked but maybe something from that disturbs this plugin?

**Comment by jaredly** [comment]
So.... I'm not sure how this would ever work.
If I do `npm install` from WSL, and then go over to powershell and type `npm run build`, it fails.
How is the vscode plugin (running from the windows side)
a) supposed to know that bs-platform was installed via WSL
b) and then run it from within wsl?

I don't know much about WSL, but I'd definitely be open to a pull-request if y'all can figure it out 🙇‍♂️

**Comment by jaredly** [comment]
My recommendation at the moment would be to `npm install` *not* from within WSL, because the straight-windows approach is fully working!

**Comment by matthewsimo** [comment]
Yep, I have a feeling this is a hangover from the previous Reason on
Windows recommended WSL install method. I'll dig in, not really a Windows
guy but I'll give it a shot..

**Comment by WesleyvHaren** [comment]
When installing bs-platform outside WSL it still doesnt work.

After some debugging I got this error:

'C:\Users\Wesley\Desktop\testing-reason\node_modules\.bin\bsb' is not recognized as an internal or external command,
operable program or batch file.
[Error - 6:25:53 PM] Request textDocument/documentSymbol failed.
  Message: Could not run bsb
  Code: -32603 

The path specified is the correct path and contains the bsb.cmd, is the Error of any help?

**Comment by matthewsimo** [comment]
Yep, that's the same error I get in the Output panel. Based on the time I spent looking into why this might happen and I think it's a VS Code on WSL Windows limitation. 

In the extension's execution `process.platform` is 'win32', even with pointing VS Code's shell to bash or starting VS Code from the cli from bash via `code .`.

When running node from WSL bash it's obviously 'linux' and since node/npm/bsplatform are all installed on this side of the fence nothing is in the window terminal's path/env so it fails. Saw a couple of threads about running VS Code as/from WSL but they were dead ends for me. Until we can essentially run the VS Code app and have it run as a Linux version and reference the bash side's runtimes don't see how this'll work (and I have no idea how electron env stuff works).

I do imagine installing a Windows version of Node/NPM/bs-platform will end up working just fine, so if you're coming in after the fact and that's acceptable just go that route. For me, I just don't want to really manage two versions of everything right now. 

Really appreciate everyone's effort - happy to have this closed for now unless someone else is more determined and wants to continue to pursue it. Thanks!

**Comment by jaredly** [comment]
Yeah, makes sense :/
