### ISSUE TITLE
Unable to use native.bin 1.0.2 with Oni Vim on macOS

### ISSUE THREAD

**Issue by cdebotton** [jaredly/reason-language-server#116]
Hello! I'm attempting to use the `native.bin` file released with `1.0.2` with Oni Vim on macOS High Sierra 10.13.2.

My config is as follows:

```tsx
export const configuration = {
    "language.reason.langaugeServer.command": "/Users/cdebotton/.config/oni/bin.native",
    "language.reason.languageServer.arguments": "",
    "language.reason.languageServer.configuration": {},
};
```

When using this binary, the reason language server never seems to start, however when using `reason-language-server.exe` from `1.0.0-beta.7`, the language server start immediately without issue. Please let me know if there's any other helpful information that I could provide!

**Comment by jaredly** [comment]
Cool
