### ISSUE TITLE
textDocument/definition fails with namespaces enabled while using LanguageClient-neovim

### ISSUE THREAD

**Issue by zploskey** [jaredly/reason-language-server#12]
If `"namespace": true` is set in `bsconfig.json` then the language server does not seem to be able to resolve other modules in the project. It gives lint errors like `[Error]Type error! File "", line 24, characters 53-62: Error: Unbound module Browser.`, and I'm not able to use go-to-definition to navigate to those other modules. Disabling namespaces makes that work as expected.

I'm using Neovim w/ LanguageClient-neovim as I have been using with ocaml-language-server.

**Comment by gaelduplessix** [comment]
@zploskey Couldn't reproduce your issue. Tried to add `"namespace": true` to `./example-project/bsconfig.json` and it still manages to find the all the modules of the project

@jsiebern Same, moved `Other.re` in a sub-directory in `example-project/src` and it is still found by the language server

Could you provide some minimal reproduction instructions please ?

**Comment by zploskey** [comment]
Maybe it's slightly more complex than I thought. Here is the full bsconfig: https://github.com/bs-puppeteer/bs-puppeteer/blob/529a6537ae2f5dbb140fb4db28d449195e6d4345/bsconfig.json

**Comment by zploskey** [comment]
If I symlink the [project](https://github.com/bs-puppeteer/bs-puppeteer) directory into the examples directory and change the client task to run that directory in the Extension Development Host, then go-to-definition works fine in the launched vscode window.

I no longer get erroneous lint errors about unbound modules in neovim.

Go to definition still does not seem to work in neovim. Here are parts of the log files for the server and client related to trying to go to the definition of another module in the project with namespaces enabled.

lsp log:
```json
Read message 
{"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":54,"line":16},"textDocument":{"uri":"file:///home/zach/src/bs-puppeteer/src/Browser.re"}},"id":22}
Got a method textDocument/definition
No path for module BsPuppeteer
Sending response {"id": 22, "jsonrpc": "2.0", "result": null}
```

LanguageClient-neovim log:
```
10:41:23 INFO main src/languageclient.rs:899 Begin textDocument/definition
10:41:23 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename, Line, Character, GotoCmd, Handle] = [String(""), String("reason"), String("/home/zach/src/bs-puppeteer/src/Browser.re"), Number(16), Number(54), Null, Bool(true)]
10:41:23 INFO main src/vim.rs:90 => Some("reason") {"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":54,"line":16},"textDocument":{"uri":"file:///home/zach/src/bs-puppeteer/src/Browser.re"}},"id":22}
10:41:23 INFO reader-reason src/vim.rs:389 <= Some("reason") {"id": 22, "jsonrpc": "2.0", "result": null}
10:41:23 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"s:Echowarn","params":["Not found!"],"id":23}
10:41:23 INFO reader-main src/vim.rs:389 <= None {"id": 23, "jsonrpc": "2.0", "result": 0}
10:41:23 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","result":null,"id":1}
10:41:25 INFO reader-main src/vim.rs:389 <= None {"method": "exit", "jsonrpc": "2.0", "params": {"languageId": "reason", "buftype": ""}}
```

If needed I can provide a simple neovim config file, but I'm not doing anything weird there.

**Comment by jaredly** [comment]
This is when you have the bs-puppeteer library open, right? Why do you expect there to be a `BsPuppeteer` module defined?

**Comment by zploskey** [comment]
BsPuppeteer is the name of the namespace module that gets created by bsb when namespaces are enabled for the bs-puppeteer project. I'm trying to go to the definition of one of the other modules in the project, not BsPuppeteer. I was hovering over the `Page` module name as part of `Page.t` when I executed the command.

**Comment by zploskey** [comment]
This wouldn't have anything to do with how the namespace name is created, would it? It looks like `FindFiles.getNamespace` just capitalizes the name and would not strip out the `-` and capitalize the letter after it.

**Comment by jaredly** [comment]
ah, hmmm ok I think I understand what's going on

**Comment by jaredly** [comment]
Fixed!
