### ISSUE TITLE
Fatal error: exception Not_found

### ISSUE THREAD

**Issue by wegry** [jaredly/reason-language-server#123]
`Fatal error: exception Not_found` only occurs in the entry point of my application with the 1.0.3 version of reason-vscode.

Try as I might, [I could not reproduce this on a smaller scale](https://github.com/jaredly/reason-language-server/issues/72#issuecomment-416150814). Unfortunately, it's proprietary code.

I did notice something interesting though. At least in the codelens list at the top of the file, _the listed modules includes the module itself_, *Demo*. That's hopefully a bug, right?

Going through other files in the codebase, the codelens at the top of the file also includes the _Demo_ module. Demo contains an array of Storybook kinds(?). The relationship between the modules looks something like this

```
Demo <- AlertDemo <- Alert
            ^
            |
            Storybook (a couple Functors)
```

`<-` in this case means that  a module 'depends on' another. Demo has a array of modules that forms the entry point of the application itself.

**Comment by wegry** [comment]
This is the `.lsp` debug messages for the root file. 

```
Setting log location: <root>/node_modules/.lsp/debug.log
[Error - 2:46:28 PM] Request textDocument/hover failed.
  Message: Failed to refmt '<root>/node_modules/bs-platform/lib/refmt.exe' --print binary --recoverable --parse re > '<root>/node_modules/.lsp/Demo.ast'
/bin/sh: 1: cannot create <root>/node_modules/.lsp/Demo.ast: Directory nonexistent
  Code: -32603 
[Error - 2:46:28 PM] Request textDocument/hover failed.
  Message: Failed to refmt '<root>/node_modules/bs-platform/lib/refmt.exe' --print binary --recoverable --parse re > '<root>/node_modules/.lsp/Demo.ast'
/bin/sh: 1: cannot create <root>/node_modules/.lsp/Demo.ast: Directory nonexistent
  Code: -32603 
[Error - 2:46:29 PM] Request textDocument/hover failed.
  Message: Failed to refmt '<root>/node_modules/bs-platform/lib/refmt.exe' --print binary --recoverable --parse re > '<root>/node_modules/.lsp/Demo.ast'
/bin/sh: 1: cannot create <root>/node_modules/.lsp/Demo.ast: Directory nonexistent
  Code: -32603 
```

**Comment by jaredly** [comment]
welll that's weird. Do you have some sort of monorepo setup? Does `<root>/node_modules/` exist?

**Comment by wegry** [comment]
It's a monolith (one repo). `<root>/node_modules/` does exist.

My bsconfig

```json5
{
  "name": "...",
  "version": "...",
  "bsc-flags": [
    "-bs-no-version-header",
    "-bs-super-errors",
    "-open Belt"
  ],
  "sources": {
    "dir": "src",
    "subdirs": true
  },
  "package-specs": {
    "module": "es6",
    "in-source": true
  },
  "suffix": ".bs.js",
  "reason": {
    "react-jsx": 2
  },
  "bs-dependencies": [
    "reason-react"
  ],
  "warnings": {
    "error": "+101"
  },
  "namespace": true,
  "refmt": 3
}
```

**Comment by wegry** [comment]
With version 1.0.4 of the plugin, this appears to no longer be an issue. I'm mystified, but also pleasantly surprised.

**Comment by jaredly** [comment]
Awesome :)
