### ISSUE TITLE
Show a better error message when there's no directory for compiled artifacts

### ISSUE THREAD

**Issue by rssfrncs** [jaredly/reason-language-server#13]
Hi,

What would be of help?

Project generated with `bsb -init . -theme basic-resaon` no modifications. 

Contents of node_modules/.lsp/debug.log

```
Sending response {"id": 0, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Failure(\"Cannot find directory for compiled artifacts. Looked at C:\\\\Repos\\\\reason\\\\lib\\\\bs, C:\\\\Repos\\\\reason\\\\lib\\\\ocaml\")Raised at file \"pervasives.ml\", line 30, characters 22-33\nCalled from file \"C:\\Users\\IEUser\\Documents\\reason-language-server\\src\\lsp\\Main.re\", line 78, characters 25-68\nCalled from file \"C:\\Users\\IEUser\\Documents\\reason-language-server\\src\\util\\Result.re\", line 10, characters 51-56\nCalled from file \"C:\\Users\\IEUser\\Documents\\reason-language-server\\src\\lsp\\BasicServer.re\", line 100, characters 13-38\n"}}
Finished
```

vscode config
```
    "reason_language_server.reloadOnChange": true,
    "reason_language_server.location": ""
```

**Comment by rssfrncs** [comment]
@jaredly ah, yeah that's working!

**Comment by jaredly** [comment]
![image](https://user-images.githubusercontent.com/112170/41361786-1b95d006-6eed-11e8-9a18-3b1604edd6d3.png)
Ok, now it will respond with this message

**Comment by frontmesh** [comment]
> ![image](https://user-images.githubusercontent.com/112170/41361786-1b95d006-6eed-11e8-9a18-3b1604edd6d3.png)
> Ok, now it will respond with this message
How to get rid of this message ? Autocomplete is working as it should, but this message is persistant.
