### ISSUE TITLE
npm install fails in master

### ISSUE THREAD

**Issue by naartjie** [jaredly/reason-language-server#131]
Against version: 0d13796b0692546f467e053d53356a6c4df58a61

Steps to reproduce:
1) git clone
2) `cd reason-language-server`
3) `npm install`

`postinstall.js` runs `bsb -make-world -backend native` which errors with:

```
Error: /Users/naartjie/Project/GitHub/reason-language-server/src/analyze/core: No such file or directory
```

It looks like `bsbconfig.json` is still pointing to some (old?) directories, which don't exist anymore.

**Comment by jaredly** [comment]
rigght, I just changed the installation setup but I haven't updated the readmy. It's now built with `esy`, so first `npm i -g esy@next`, and then running `esy` should install & build everything

**Comment by naartjie** [comment]
Ah, that works, thanks!!

I was going to have a go at updating the README but I see you beat me to it 🐎
