### ISSUE TITLE
Error: Can't find module name

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#132]
After bump RLS from `1.0.2` to `1.0.4` in Atom plugin I started seeing this error:

<img width="755" alt="screen shot 2018-09-08 at 18 07 00" src="https://user-images.githubusercontent.com/4244251/45261490-58738700-b436-11e8-8469-235ad2fd4b92.png">

Notes from yesterday: I created a file w/ non-uniq name. After that RLS started throwing these errors (I think on every request). When I fixed all errors in the code, RLS was still unhappy. Then I switched to term and run `bsb -clean-world -make-world` -> restarted RLS -> things were back to normal.

I tried to reproduce it today but now RLS acts differently:

<img width="1276" alt="screen shot 2018-09-09 at 13 49 55" src="https://user-images.githubusercontent.com/4244251/45261702-b4d8a580-b43a-11e8-9a67-9f1be5c303b6.png">

I also was installing/removing some deps yesterday, but still can't repro it by reinstalling some deps.

**Comment by alexfedoseev** [comment]
Faced `Can't find module name` error again. I think it's related to deps change (I removed one, then installed one) but it's not 100%.

**Comment by Dragna** [comment]
it seems that I have the exact same problem. same error on autocompletion too

**Comment by tcoopman** [comment]
I have the same problem with vscode:
```
[Error - 3:51:20 PM] Request textDocument/hover failed.
  Message: Can't find module name
  Code: -32603 
```

**Comment by jaredly** [comment]
hrmmmm that's very weird

**Comment by tcoopman** [comment]
Any way I can investigate more?

**Comment by jaredly** [comment]
@tcoopman could you make an example repo that has the code you're using?

**Comment by tcoopman** [comment]
This is a repo where I have the error: https://github.com/tcoopman/reason-language-server-error-132

There is no code only some imports.

I also got this response when I asked about it on discord:

> Dragna: @tcoopman when using an older version, the problem is gone, but I don't understand what is doing that :/

**Comment by reallyely** [comment]
@tcoopman , I read your bit about copying files to a different folder to get things working. I had a hunch and reduced it one step further. I was able to get the language server running again by opening my .bsconfig, cutting out it's contents, saving, then pasting back the contents and saving. Functionality has appeared to have returned immediately.

**Comment by tcoopman** [comment]
@reallyely that doesn't fix it for me.

I have the same issue with the latest release, the error message changed a bit though: `Can't find module name for path /home/thomas/Workspace/tmp/reason-language-server-error/src/e2e.re`

**Comment by jaredly** [comment]
ahhh it's the module name mangling thing again.

**Comment by tcoopman** [comment]
Tried it, seems to work for me. Thanks!

**Comment by jaredly** [comment]
ok, I think I squashed this for good. feel free to reopen if it recurs
