### ISSUE TITLE
Show types for module members

### ISSUE THREAD

**Issue by RawToast** [jaredly/reason-language-server#139]
First, thanks for the plugin!

Whilst this issue description relates to VSCode, I believe this would be a useful addition possible for any editor.

From the previous language server, I am used to having CodeLens show the types for all values. Having the type information visible is very useful when building Modules and Functors. However,  it seems like I can only enable VSCode's CodeLens to show values outside of a module by enabling `Reason_language_server: Per_value_codelens`.

It would be great to provide an option to show the types of the module members in the same way `Per_value_codelens`

**Comment by jaredly** [comment]
Good idea! The "per value codelens" feature is pretty limited at the moment (I don't personally use it).
Here's the place to poke at https://github.com/jaredly/reason-language-server/blob/master/src/lsp/MessageHandlers.re#L333-L338
If you add a branch to the `switch` that's something like
```
| Module(Structure({topLevel})) => ... have a codelens for each toplevel item in here
```
then I think that's all you'd need?

(see the type definition here https://github.com/jaredly/reason-language-server/blob/master/core/SharedTypes.re#L233-L237)
