### ISSUE TITLE
go-to-definition fails for dependencies with namespaces enabled

### ISSUE THREAD

**Issue by zploskey** [jaredly/reason-language-server#145]
I can't seem to go to a definition in a dependency that has enabled namespaces. RLS fails to find a path to the module. This may be related to #12. It's close to the same problem but it affects dependencies with namespaces instead of the current project itself.

This is what is logged when trying to use go-to-definition on the function `BsSpectacle.Theme.createTheme`.

```
Read message 
{"jsonrpc":"2.0","id":95,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///home/zach/src/intro-to-reason/src/Presentation.re"},"position":{"line":2,"character":35}}}
[server] Got a method textDocument/definition
[server] processing took 0.00786781311035ms
No path for module BsSpectacle
Sending response {"id": 95, "jsonrpc": "2.0", "result": null}
```

It also complains about not finding a path to the module for the hover action but it still returns the type definition.

I've tested this on 1.1.1 and latest master (65fce5db7dd65bf0a9e27bbf519757965c7484c0) on Ubuntu 18.04.

EDIT: Still an issue on 1.2.0.

**Comment by jaredly** [comment]
it looks like bs-spectacle doesn't build at all, it's still expecting bs-platform 2.x

**Comment by zploskey** [comment]
I'm using the git master here https://github.com/piotrdubiel/bs-spectacle. They need to cut a new release. The presentation works fine on that.

**Comment by zploskey** [comment]
Confirmed fixed in this commit: https://github.com/jaredly/reason-language-server/commit/e6e1391fe689e66880530b5fa009d4a2dc80c442
