### ISSUE TITLE
Type details on hover doesn't distinguish between different variable types

### ISSUE THREAD

**Issue by simonolander** [jaredly/reason-language-server#148]
For example, the function 
```ocaml
let f = (a, b) => (a, b);
```
is displayed as having type `('a, 'a) => ('a, 'a)`, but it should be `('a, 'b) => ('a, 'b)`.

**Comment by jaredly** [comment]
thanks for the report! It's fixed in master, will release soon

**Comment by simonolander** [comment]
Cool :smile:
