### ISSUE TITLE
Can't display types info   with `namespace` set to true 

### ISSUE THREAD

**Issue by beizhedenglong** [jaredly/reason-language-server#149]
os: macOS v10.13.4
editor: vs code v1.22.2
reason-vscode: v1.2.0
bs-platform: v4.0.5
debug info: [debug.log](https://github.com/jaredly/reason-language-server/files/2436730/debug.log)

**Comment by jaredly** [comment]
hmm, I can't reproduce :( could you try cloning the https://github.com/reasonml-community/reason-react-example and see if type information works with that project?

**Comment by beizhedenglong** [comment]
@jaredly It works fine with new release version.
