### ISSUE TITLE
v1.2.3 crash: Invalid_argument("String.sub / Bytes.sub")

### ISSUE THREAD

**Issue by cem2ran** [jaredly/reason-language-server#151]
I'm getting the following error when opening a react-native reason project, that worked fine <1.2.2.  
Let me know if you need any additional info:

```
Invalid_argument("String.sub / Bytes.sub")Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "string.ml" (inlined), line 47, characters 2-23
Called from file "util/MerlinFile.re", line 107, characters 23-67
Called from file "src/analyze/BuildSystem.re", line 108, characters 28-59
Called from file "util/Monads.re", line 203, characters 18-24
Called from file "src/analyze/State.re", line 117, characters 24-60
Called from file "src/analyze/State.re", line 493, characters 24-73
Called from file "src/lsp/NotificationHandlers.re", line 75, characters 24-72
Called from file "src/lsp/BasicServer.re", line 84, characters 11-35
```

https://gist.github.com/cem2ran/fe58f1ba4e826a3808c5ded245488785

**Comment by cortopy** [comment]
I can reproduce with same versions. By rolling back to 1.2.1 I don't get the error

**Comment by broerjuang** [comment]
I encounter the same issue, and following @cortopy suggestion is working now. 

1. Download the last version of this extension [here](https://jaredly.gallery.vsassets.io/_apis/public/gallery/publisher/jaredly/extension/reason-vscode/1.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage)
2. Change the extension to `.vsix`
3. using command pallets from VS Code (Install from VSIX) 
<img width="599" alt="screen shot 2018-10-08 at 1 50 59 am" src="https://user-images.githubusercontent.com/7804066/46585568-be3a4980-ca9c-11e8-88f6-d1884bd1ca8b.png">

**Comment by nlfiedler** [comment]
I am seeing this with a BuckleScript project as well, so not native specific.

**Comment by jaredly** [comment]
ahh this is more of @bsansouci's change, I'll fix

**Comment by bsansouci** [comment]
Oh sorry about this! I can fix too

**Comment by nlfiedler** [comment]
That was fast, thanks!
