### ISSUE TITLE
On windows make change to a file  trigger a full recompile very offen

### ISSUE THREAD

**Issue by ArcherDs** [jaredly/reason-language-server#165]
On windows when used with vscode x64,
let bsb -make-world -w run in the background,
Change a file and save trigger the bsb recompile files which not change ,
When i disable the plugin in vscode , it recompile incrementally

On Ubuntu this works properly

**Comment by jaredly** [comment]
I should really add a warning about running `bsb -make-world -w` in the background --- the vscode plugin runs bsb for you automatically, so you shouldn't really be running it separately

**Comment by ArcherDs** [comment]
Oh, i didn't notice the plugin build it automatically, after  a try , the result seens unstable, sometimes  the build  procedure works very fast ,the other times it complete after a long wait (about >30 seconds,or after i made a second change ,it made the first change to the result),i didn't sure why these happens , i think this problem is windows only .

**Comment by ArcherDs** [comment]
After 1.4.0 ，I turned off the autorebuild and run bsb by hand and it works as expect , this is a way to get around with the build problem on windows . Thanks for the great wok
