### ISSUE TITLE
Unable to `yarn add` new packages  with VSCode running and .re file opened.

### ISSUE THREAD

**Issue by daniloraisi** [jaredly/reason-language-server#176]
First off, this is a really cool extension to VSCode!

I'm facing a problem when trying to add packages using Yarn with VSCore + Reason LS running.

I extract this error from `yarn-error.log`:
> `Error: EBUSY: resource busy or locked, unlink 'D:\Documents\Projects\Pessoal\reason-notes-app-client\node_modules\.lsp\debug.log'`

To get this working I need to close any .re file opened, reload VSCode window and then add package.

Using `npm install` it works as expected.

**Comment by jaredly** [comment]
hrmmm I wonder why yarn wants to remove `.lsp` :/ that's annoying

**Comment by daniloraisi** [comment]
I did some tests and research and basically I think this is caused because yarn build everything all time you add new package.

Maybe I'm wrong, and misunderstand it.
