### ISSUE TITLE
File "", line 1: Error: Missing dependency Nfa-MyNewProject in search path (1,1)

### ISSUE THREAD

**Issue by joelonsql** [jaredly/reason-language-server#180]
This only happens when using bsconfig.json package-specs module "es6-global".

Seems related to old issue: https://github.com/jaredly/reason-language-server/issues/68

I get this error for all modules, but just the one called "Nfa".

Everything works OK though, the generated .js code looks fine and works with Firefox.

The error messages are annoying though.

Here is the relevant part from my .lsp/debug.log:

type error here File "", line 1:
Error: Missing dependency Nfa-MyNewProject in search path
Sending notification {"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///Users/joel/src/my-new-project/src/Regex.re", "diagnostics": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "message": "File \"\", line 1:\nError: Missing dependency Nfa-MyNewProject in search path", "severity": 1}]}}

**Comment by jaredly** [comment]
> I get this error for all modules, but just the one called "Nfa".

I don't understand that sentence. Do you get the error for all, or just one?

Also, can you reproduce the error in this example repo? (after changing the specs to `"es6-global"`) https://github.com/reasonml-community/reason-react-example
