### ISSUE TITLE
Error building esy project when in a monorepo with a bucklescript frontend

### ISSUE THREAD

**Issue by mscharley** [jaredly/reason-language-server#193]
My project structure is as follows:

```
├── package.json (npm)
└── packages
    ├── backend
    │   └── package.json (esy)
    └── frontend
        └── package.json (npm)
```

I have a workspace setup in VSCode with three top-level folders, `/`, `/packages/backend` and `/packages/frontend`.

**/node_modules/.lsp/debug.log**

```
{"jsonrpc":"2.0","id":2,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///Users/matthewscharley/Code/smart-reason/packages/backend/src/Cohttp_server.re"}}}
[server] Got a method textDocument/codeLens
[server] processing took 0.00405311584473ms
Found a `dune` file at /Users/matthewscharley/Code/smart-reason/packages/backend/src
]] Making a new jbuilder package at /Users/matthewscharley/Code/smart-reason/packages/backend/src
=== Project root: /Users/matthewscharley/Code/smart-reason/packages/backend
Detected `esy` dependency manager for local use
Sending response {"id": 2, "jsonrpc": "2.0", "result": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "command": {"title": "Unable to load compilation data: Could not find local build dir", "command": ""}}]}
```

**/packages/backend/node_modules/.lsp**

Doesn't exist.

The log files look correct, but I'm noticing that there is an _esy folder that's popped up in the root of my project now. It could be that RLS isn't changing folder to the project root before executing the esy command.

The frontend project, which is BuckleScript + NPM works perfectly.

**Comment by mscharley** [comment]
It's worth noting that if I open VS Code in the backend project only, it works correctly.

**Comment by mscharley** [comment]
Oh, this is with version 1.3.0 of the VS Code extension.

**Comment by jaredly** [comment]
excellent :)

**Comment by mscharley** [comment]
Err. Did you mean to close this Jaed?

**Comment by jaredly** [comment]
oh wait, sorry! I somehow read "this is *fixed* with version 1.3.0"

**Comment by mscharley** [comment]
Oops! No, new issue with 1.3.0. 1.2.6 didn't even pick up my project correctly at all, so progress!

**Comment by nielmond** [comment]
I'm getting this too while playing around with this project https://github.com/anmonteiro/reason-graphql-fullstack which has a similar structure. @mscharley I couldn't even get it to work by opening VS Code in the backend folder (specifically this folder https://github.com/anmonteiro/reason-graphql-fullstack/tree/master/src/server) -- does that still work for you with 1.4.0? I couldn't get your symlink approach to work that you mentioned in #162 either.

**Comment by mscharley** [comment]
The backend folder is working directly as of 1.4.0. The symlink is no longer necessary either, RLS picks up esy and dune and just works, the only issue I'm having is the apparently folder changing issue when the esy project isn't in the project root.

**Comment by nielmond** [comment]
@anmonteiro Thanks for the suggestion. Opening with `esy @server code .` did fix the "Cannot find local build dir" error; however, now there are new problems. In the console of VS Code is the error
```
File "command line", line 1:Error: Unbound module Pervasives
```
for both main.re and schema.re. 

Looking in .lsp/debug.log on startup, it seemed to be going OK and then this happened:
```
>> Build system running: esy
>>> stdout

>>> stderr
info building graphql_ppx@0.2.8@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: graphql_ppx@0.2.8
    # esy-build-package: pwd: ~/.esy/3________________________________________________________________/b/graphql__ppx-0.2.8-b650de8d
    # esy-build-package: running: 'dune' 'build' '@graphql_ppx'
    esy-build-package: unable to resolve command: dune
    
  building graphql_ppx@0.2.8
esy: exiting due to errors above
Affected files: 
Cleaning bsconfig.json
```

**Comment by Hossman333** [comment]
Hello! I know this is an old issue, but I solved the `Unbound module Pervasives` by cleaning the environment and re-installing everything.

You can clean it by running:

```
esy b dune clean
```
And then I just re-ran `esy` and reloaded VSCode.
