### ISSUE TITLE
"Could not find local build dir" when a dune file is present (in addition to bsb-native).

### ISSUE THREAD

**Issue by cristianoc** [jaredly/reason-language-server#194]
This started happening since version 1.3.0 on [genType](https://github.com/cristianoc/genType).
The project is normally built using bsb-native, but it's also buildable with dune, so it has a couple of dune files.
If the dune files are removed, all is well.

**Comment by jaredly** [comment]
ah yeah, that makes sens

**Comment by jaredly** [comment]
I've been planning on making a vscode setting where you can specify which build system you want to use, when it's ambiguous

**Comment by cristianoc** [comment]
@jaredly is there some workaround for now, other than deleting the dune file?

**Comment by jaredly** [comment]
@cristianoc I threw this together -- could you see if it works in your case? https://github.com/jaredly/reason-language-server/pull/206/files

**Comment by cristianoc** [comment]
@jaredly yes something like that is perfect.

**Comment by cristianoc** [comment]
I'll try it as soon as a new release of RLS is out.

**Comment by jaredly** [comment]
I haven't this feature it b/c I haven't tested it yet :) will probably test it out today or tomorrow. cc
