### ISSUE TITLE
Expand PPX

### ISSUE THREAD

**Issue by sgrove** [jaredly/reason-language-server#200]
It'd be nice to be able to see the full ppx expansion of some code. It'd help a lot while developing the ppx, and also it might help to demystify the ppx for people new to the idea.

**Comment by bryphe** [comment]
Cool idea @sgrove ! 

When I started with Reason / OCaml, ppx's were one of the most confusing concepts to learn. Being able to see the expanded syntax would help remove that magic and make it clear what's happening under the hood.

**Comment by cem2ran** [comment]
Would be quite helpful! @sgrove how do you imagine this being presented visually?

Some ideas:
1. in a separate pane similar to markdown preview
2. On hover on: [@my_ppx...

**Comment by thangngoc89** [comment]
related 
https://github.com/jaredly/reason-language-server/issues/47

**Comment by jchavarri** [comment]
This was added in https://github.com/jaredly/reason-language-server/commit/5aff8455ef64ff524d526d251c27368ed52f4f3e

**Comment by mrmurphy** [comment]
@anmonteiro you can close this now as @jchavarri said.
