### ISSUE TITLE
zsh + vscode: Could not run bsb

### ISSUE THREAD

**Issue by seprich** [jaredly/reason-language-server#213]
To reproduce the problem:
1. Install the snap version of VSCode on Ubuntu 18.04.1 LTS
2. Install the reason-vscode extension
3. Change your default shell to zsh (if not already). Also install oh-my-zsh (perhaps relevant or not).

Now when launching from the desktop launcher, the language server fails to launch bsb;
Snippet from the node_modules/.lsp/debug.log:
```
{"jsonrpc":"2.0","id":10,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///home/seprich/bs-yarp/test/TestUtil.re"},"range":{"start":{"line":39,"character":32},"end":{"line":39,"character":32}},"context":{"diagnostics":[]}}}
[server] Got a method textDocument/codeAction
[server] processing took 0.0100135803223ms
Sending response {"id": 10, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Could not run bsb (ran /home/seprich/bs-yarp/node_modules/.bin/bsb -version). Output: "}}
```

As a contrast if I launch vscode from command line with:
```
SHELL=/bin/bash vscode
```
Then it works fine. You could now argue that this is really a vscode bug. However maybe if this reasonml plugin had a configuring option for setting the shell explicitly it would solve this problem elegantly. Or better yet: not to depend on a shell at all avoiding this vulnerability.

**Comment by jaredly** [comment]
hrmmmm. What happens if you run `/home/seprich/bs-yarp/node_modules/.bin/bsb -version` from your zsh shell?

**Comment by jaredly** [comment]
If you launch vscode form the command-line without the `SHELL` env variable, does it also still work?
My guess is vscode's reading env variables from your `.bash_profile` or something, and your environment setup is only in `.zshrc`

**Comment by seprich** [comment]
Yes, it actually works from zsh command line also without setting SHELL ... so the problem exists only when launched from snap launcher.. ok this seems now more of a bug in how snap launches vscode. Or vscode problem.

**Comment by seprich** [comment]
There must be something wrong in the way how vscode is packaged into a snap package. I think this issue ticket can be closed.

**Comment by mellson** [comment]
If others run into this my problem was a space in the path - #449
