### ISSUE TITLE
Use VSCode's withProgress API to show where the compilation's at

### ISSUE THREAD

**Issue by bloodyowl** [jaredly/reason-language-server#214]
currently the VSCode extension compiles the files in the background, it's instant on small projects, but take longer as the file you saved gets more dependents files.

it'd be nice to indicate in the IDE that the compilation is still running using the `withProgress` API, with the possibility to turn it off using a flag in settings.

what would you think about this? if it seems like a good idea to you I can start working on it and create a PR.

**Comment by jaredly** [comment]
That sounds excellent! Let me know if you get stuck with anything
