### ISSUE TITLE
LICENSE - Sorry for asking here but found no better place 

### ISSUE THREAD

**Issue by frank-dspeed** [jaredly/reason-language-server#219]
Can I have this or Redistribute this under Apache-2.0 ? A simple comment from the creator would be enought for me :+1: 

Most best would be to Offer this here Directly under both LICENSES but the allowens would be enough for me :)

**Comment by jaredly** [comment]
Given that this is a user-facing tool and not a library, why do you need it under apache-2.0?

**Comment by frank-dspeed** [comment]
@jaredly because i can't add a extra license to some packages that get used in a bigger project. Don't blame me for that :) its not my idea i am not a laywer i don't understand such needs. I my self would simply add the mit license file some where deep in the project as encrypted bits :).

but good question. Sorry that i don't got a answer on that

**Comment by thangngoc89** [comment]
What's wrong with MIT anyway?

**Comment by frank-dspeed** [comment]
@thangngoc89 i don't know it as i have written befor as far as i understand MIT you can do anything but need to have a copy of the Original License some where.

For me mySelf this sounds do able. Anyway a big Company i don't want to Publish the Name wants to use Apache 2.0 Licensed stuff only. And i am not in the Position to Judge that requirment.

**Comment by jaredly** [comment]
Right, I understand that some companies only want to use libraries that are under certain licenses. Are you using reason-language-server as a library? or as a user-facing tool? Because in the latter case I don't think the differences between licenses matter nearly as much.

**Comment by frank-dspeed** [comment]
@jaredly it should get integrated into a distributed SaaS, PaaS implamentation

**Comment by jaredly** [comment]
Ok yeah I'm fine with you redistributing under Apache 2.0 -- don't know if you need to get permission from all the contributors though 🤷‍♂️

**Comment by frank-dspeed** [comment]
@jaredly no i don't think that this will be needed as its easy to multi license a product all or some contributors at last would need to complain against it and thats most time to much effort for them so your permission as project owner and so leader is total fine thats what the lawyer sayed.

Thanks in advance!
