### ISSUE TITLE
Server runs build on save when autoRebuild set to false

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#222]
I added `autoRebuild` setting to Atom integration but it doesn't seem to work.

Config is sent to the server:
![image](https://user-images.githubusercontent.com/4244251/50503388-affb3880-0aa1-11e9-93a7-fa79c39a51bd.png)

But after I hit save server still builds the project.

**Comment by jaredly** [comment]
I'm not sure how much I can diagnose without the debug.log information. Could you paste that here?

**Comment by alexfedoseev** [comment]
Sorry, missed your response. But it's fixed in Atom integration.
