### ISSUE TITLE
In esy 0.5.6 `esy -q sh -- -c 'echo $OCAMLLIB'` doesn't work anymore

### ISSUE THREAD

**Issue by jchavarri** [jaredly/reason-language-server#235]
esy seems to have changed some behavior lately, and the command that [used to work](https://github.com/jaredly/reason-language-server/blob/940869cf6a3a6acb8992a38d45d49ee065e8f6c4/src/analyze/BuildSystem.re#L243):

```
esy -q sh -- -c 'echo $OCAMLLIB'
```

doesn't work anymore. The fix is to remove the `--`:

```
esy -q sh -c 'echo $OCAMLLIB'
```

However, changing it will break folks on previous versions of esy.

@jaredly do you have any pointers on how you'd prefer to fix this?

**Comment by jaredly** [comment]
We do version detection for Bsb etc. -- I'd say let's add version detection for esy & handle it accordingly

**Comment by jordwalke** [comment]
This is what I did in [vim-reasonml](https://github.com/jordwalke/vim-reasonml)

But also, I think now we could just require everyone use the latest esy going forward, since esy's API is more stable now.

**Comment by jordwalke** [comment]
You can see how I execute the various esy commands and do version detection in that plugin for inspiration.
