### ISSUE TITLE
Links in comments will result in comment terminator not parsed, thus highlighting the remaining lines as comments

### ISSUE THREAD

**Issue by ambientlight** [jaredly/reason-language-server#241]
Steps to reproduce:
1. clone https://github.com/SentiaAnalytics/bs-css.git
2. in vsCode, open `src/Css.re` on line 1328. Notice:

<img width="1126" alt="screen shot 2019-02-06 at 1 50 22 pm" src="https://user-images.githubusercontent.com/14032724/52322970-2c285a80-2a16-11e9-8493-a249adb1702a.png">

**Comment by mlms13** [comment]
Does the syntax highlighting code come from upstream? I noticed the same issue somewhere else (possibly Reason syntax highlighting on Github?)

**Comment by jaredly** [comment]
Yeah, I've just copied it from elsewhere

**Comment by nireno** [comment]
I assume something's getting confused with the single-line comment `//` in `http://`. If I close the multi-line comment on a new line the problem goes away.

**Comment by hartmut27** [comment]
I've tested the issue on different ways with the mentioned git clone source code and the commentaries, 
but I cannot reproduce.
Eventually the bug is no bug any more...

**Comment by ambientlight** [comment]
should it be closed in such case?

**Comment by hartmut27** [comment]
Yes, imho please close the issue
