### ISSUE TITLE
Type constructors not showing up in autocomplete

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#25]
I have this type `Error | Warning | Info | Log`, as you can see

![image](https://user-images.githubusercontent.com/112170/41362267-2afa2e10-6eee-11e8-8899-909ed98e6a9e.png)

but I don't get autocomplete for the constructors

![image](https://user-images.githubusercontent.com/112170/41362279-30878a08-6eee-11e8-834b-10f3536bb5dd.png)

**Comment by rssfrncs** [comment]
Hi not sure if hijacking but in Windows 10 i'm not getting any autocomplete for records?

![image](https://user-images.githubusercontent.com/7808978/41403779-a026a2d4-6fbd-11e8-9b0e-775e0be0aa19.png)

I can raise as separate issue if it helps.

**Comment by jaredly** [comment]
Yeah, let's make this a separate issue -- the implementation will be a little different.

**Comment by jaredly** [comment]
done to both
