### ISSUE TITLE
Logs in node_modules when it didn't already exist

### ISSUE THREAD

**Issue by texastoland** [jaredly/reason-language-server#250]
I have a snippet folder without `node_modules`. It would also happen on a non-esy opam project. I notice logs appear in `./node_modules/.lsp` when I get ready to commit. Easy to work around but inconvenient.

**Comment by jaredly** [comment]
What would be the preferred location?

**Comment by texastoland** [comment]
I suppose directly in the user directory? Or maybe only if there's no `package.json`? I really found it clever when I realized why. I'll probably end up ignoring `node_modules` in my root directory with a comment why.
