### ISSUE TITLE
build_system_override_by_root  setting documentation

### ISSUE THREAD

**Issue by tomvardasca** [jaredly/reason-language-server#256]
Hi,

Is it possible to provide examples on how to use `build_system_override_by_root`?

My log currently is as follows: 
```
[Error - 2:54:28 PM] Request textDocument/documentSymbol failed.
  Message: Could not find local build dir
  Code: -32603 
[Error - 2:54:28 PM] Request textDocument/hover failed.
  Message: Could not find local build dir
  Code: -32603 
[Error - 2:54:28 PM] Request textDocument/hover failed.
  Message: Could not find local build dir
  Code: -32603 
[Error - 2:54:29 PM] Request textDocument/hover failed.
  Message: Could not find local build dir
  Code: -32603 
```

Kind regards

**Comment by michaelboulton** [comment]
I ran into this a few days ago and managed to figure it out from https://github.com/jaredly/reason-language-server/pull/206/files

You need to specify key: value pairs where each key is the absolute path to a folder, and the value is one of these https://github.com/jaredly/reason-language-server/blob/b7faf68f3f854262047d8e6ca48ecd63331d0825/editor-extensions/vscode/package.json#L55-L60

```jsonc
{
  "reason_language_server.build_system_override_by_root": {
    "file:///home/example/project/": "dune:esy",
    // "file:///home/example/project/": "bsb:4.0.7",
  }
}
```

Reload the window afterwards and it should pick it up.

If I try to use bsb for this in a dual esy/bsb project I get an error `Unable to read file:///home/example/project/bsconfig.json` even though it definitely exists though (and I can build outside of vscode) but I suppose that's a separate issue

**Comment by tomvardasca** [comment]
Thank you very much for that info :)

Kind regards
