### ISSUE TITLE
bs-platform 5.0.0-dev bsconfig "namespace" string unsupported

### ISSUE THREAD

**Issue by MoOx** [jaredly/reason-language-server#257]
bs-platform 5.0.0-dev supports now a custom namespace so you can do the following

```json
{
  "name": "bs-react-native",
  "namespace": "react-native",
}
```

Currently RLS doesn't support this as it fails to find `ReactNative.*` (but this works with `bsb -make-world` in my terminal)

**Comment by MoOx** [comment]
Oops. I used incorrectly cmd+return. Let me edit the description :)

**Comment by MoOx** [comment]
bs-platform 5.0.0-dev supports now a custom namespace so you can do the following

```json
{
  "name": "bs-react-native",
  "namespace": "react-native",
}
```

Currently RLS doesn't support this as it fails to find `ReactNative.*` (but this works with `bsb -make-world` in my terminal)

**Comment by MoOx** [comment]
It seems the fix should be hard here https://github.com/jaredly/reason-language-server/blob/cbbdf9016a983a9bea2ebb2d03d2089b258cde3a/src/analyze/FindFiles.re#L148-L151

I will try to make a PR

**Comment by Emilios1995** [comment]
@jaredly I very much need this feature. When are you planning to release? Is it safe if I clone master and build the release myself?
