### ISSUE TITLE
bs-platform@6.0.1-dev throwing out "Invalid cmt format - probably wrong ocaml version"

### ISSUE THREAD

**Issue by wegry** [jaredly/reason-language-server#263]
When using the latest dev version bs-platform, it looks like the language server is getting stuck on something. Maybe it's related to the OCaml 4.06 update?

From the debug.log.

> Sending response {"id": 2, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Invalid cmt format - probably wrong ocaml version"}}

**Comment by thangngoc89** [comment]
Yep. Definitely related to 4.06 update. LSP needs to be able to detech bs-platform 6 and uses 4.06 formats
