### ISSUE TITLE
Bucklescript config subdirs throws error when set to false

### ISSUE THREAD

**Issue by baransu** [jaredly/reason-language-server#268]
Setting in Bucklescript config `"subdirs": false` breaks the language server.
```
{
  "dir" : "src",
  "subdirs" : false
}
```
This should be handled the same as no "subdirs" field.

**Comment by baransu** [comment]
I assume it's just a matter of changing:
```reason
| None => [current /+ dir]
| Some(Json.True) => // impl
```
to 
```reason
| None | Some(Json.False) => [current /+ dir]
| Some(Json.True) => // impl
```
in this function
https://github.com/jaredly/reason-language-server/blob/0289627ed7e9721fc6f366cf7a00de92c3051eab/src/analyze/FindFiles.re#L32-L56

**Comment by ntwilson** [comment]
Is there a version of the extension where this works?  Or is there a workaround?  Right now it's preventing us from adding any third-party packages if that third-party package has `"subdirs" : false` in their bsconfig file, since then we can't do any editing in VS Code anymore.

**Comment by baransu** [comment]
@ntwilson I also had the same problem with `tablecloth` 😉 I'll try to submit a fix soon and I hope it will be released soon. Current workaround would be to change `bsconfig.json` in `node_modules`. While it's not perfect it should work for development :)

**Comment by ntwilson** [comment]
Thanks @baransu!  I'll watch for that.  Changing the bsconfig.json in node_modules is annoying but shouldn't be too bad.  I'll see if the rest of the team will go for that.  Otherwise we'll just wait.

**Comment by jaredly** [comment]
I'm trying to fix an issue with appveyor, but once that's done I should have a new release out with this fix in it :)
