### ISSUE TITLE
Number of type errors in BSB generated React project (builds fine)

### ISSUE THREAD

**Issue by rssfrncs** [jaredly/reason-language-server#27]
Generated a React project using `bsb -init my-react-app -theme react`, made no other modifications (except building the project) and getting various errors highlighted by the extension:

![image](https://user-images.githubusercontent.com/7808978/41403078-e3b935cc-6fbb-11e8-886e-bdcc8442ef24.png)

![image](https://user-images.githubusercontent.com/7808978/41403100-f3c08e7a-6fbb-11e8-88c0-ae76aeb51f90.png)

The project builds fine running `yarn build`

**Comment by rssfrncs** [comment]
Not sure

**Comment by jaredly** [comment]
Thanks for highlighting! I haven't checked on jsx support yet, I'll look into it

**Comment by jaredly** [comment]
Ok, this should be good! https://github.com/jaredly/reason-language-server/releases/tag/1.0.0-beta.3
