### ISSUE TITLE
Usable inside bucklescript repository

### ISSUE THREAD

**Issue by phated** [jaredly/reason-language-server#273]
I (and other people I've talked to) have found it really difficult to work on the BuckleScript project directly because the language server doesn't detect the BuckleScript repository as a valid project.  Is there something we could do to special-case that repository so more people can contribute on it?

**Comment by jaredly** [comment]
That would be great! Given that bucklescript doesn't use dune (the de-facto standard build system for ocaml native), this will take a bit of work to support. Here's what I think it would involve:
- adding a `Custom` constructor to [BuildSystem.t](https://github.com/jaredly/reason-language-server/blob/master/src/analyze/BuildSystem.re#L27)
- require users to specify in their vscode/settings.json that they want to use that Custom type for the current workspace
- probably a bunch of little changes to make everything work

**Comment by phated** [comment]
I've just been using https://github.com/ocaml/ocaml-lsp and https://github.com/ocamllabs/vscode-ocaml-platform for my ocaml work, so closing this.
