### ISSUE TITLE
bsc is invoked with incorrect ppx path when using ppx in a non-native project

### ISSUE THREAD

**Issue by ohana54** [jaredly/reason-language-server#278]
In a project that uses Bucklescript for JS compilation and a PPX (specifically https://github.com/ryb73/ppx_decco) I get a top-level error for every file:
`sh: <project-root>/lib/bs/native/ppx_decco.native: No such file or directory`

Offending bsc flag from the debug log:
`-ppx '<project-root>/lib/bs/native/ppx_decco.native'`

I think this is because we convert ppx paths for every build system, although it should be a workaround for bsb-native only:
https://github.com/jaredly/reason-language-server/blob/master/util/MerlinFile.re#L22
Called from here:
https://github.com/jaredly/reason-language-server/blob/master/util/MerlinFile.re#L435

I tried running the extension locally and was able to work around it by doing the following:
1. skip calling `fixPpx`. Now it still failed with the following (from debug log):
`sh: ppx_decco: command not found`
2. Change `ppx-flags` from "ppx_decco" to "@ryb73/decco/ppx/ppx_decco.sh"
(`ppx_decco` is a node script residing in node_modules/.bin which spawns the actual ppx, maybe the extension doesn't work with bin scripts?)

Reproduction:
1. Create a new project with `bsb -init my-new-project -theme basic-reason`
2. Run `npm i @ryb73/decco`
3. Modify `bsconfig.json` as described here:
https://github.com/ryb73/ppx_decco#how-do-i-install-it
4. Open VS Code

Environment:
OS: Mac OSX
bs-platform: 5.0.2
Extension version: 1.6.0
Settings:
```
{
  "reason_language_server.per_value_codelens": true,
  "reason_language_server.autoRebuild": false,
  "reason_language_server.show_debug_errors": true,
  "reason_language_server.useOldDuneProcess": false
}
```

**Comment by ohana54** [comment]
I dug a bit more, and doing only this:
> Change ppx-flags from "ppx_decco" to "@ryb73/decco/ppx/ppx_decco.sh"

makes it work, without skipping `fixPpx`. I guess the pattern match logic in `fixPpx` causes it to skip the transformation since the .merlin file now looks like this:
`FLG -ppx /Users/<user>/<project-root>/node_modules/@ryb73/decco/ppx/ppx_decco.sh`
Instead of this:
`FLG -ppx ppx_decco`

**Comment by jaredly** [comment]
@ohana54 hmm yeah it sounds like modifying https://github.com/jaredly/reason-language-server/blob/master/util/MerlinFile.re#L22 to only run when we're under `bsb-native`, and then adding logic to check `node_modules/.bin` for the executable would do the trick here. Let me know if you need any more pointers!

**Comment by ohana54** [comment]
Thanks, I don't have much experience but will do my best to create a PR.
