### ISSUE TITLE
bsppx error in new react-reason project

### ISSUE THREAD

**Issue by jwhitley** [jaredly/reason-language-server#282]
### Description

In a new reason-react project, VSCode using reason-vscode generates errors in the Problems window for any Reason files in the project; see repro steps and attached debug.log for details.

### Repro steps

Prerequisites: Have VSCode (1.34.0) installed with the reason-vscode extension (1.6.0)

1. Follow the QuickStart instructions at the [ReasonReact homepage](https://reasonml.github.io/reason-react/en/), ala: 
    ```
    yarn global add bs-platform
    bsb -init reason-vscode-test -theme react-hooks
    cd reason-vscode-test
    yarn install && yarn start
    ```
2. In a separate terminal: `yarn run webpack`
3. Run `code .` from the CLI to start VSCode in this new project.
4. Open `Component1.re`, observe that there's a Problem on line 1, column 1, ala:
    ```
    sh: /Users/whitley/src/todomvc-reason/src/reason-vscode-test/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3: No such file or directory
    File "", line 1:
    Error: Error while running external preprocessor
    Command line: '/Users/whitley/src/todomvc-reason/src/reason-vscode-test/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3' '/var/folders/x6/bd5b_zh50cg2fp5jzzv30zn80000gn/T/camlppxb45400' '/var/folders/x6/bd5b_zh50cg2fp5jzzv30zn80000gn/T/camlppx1a1ef3'
    ```

### Notes

I note that #126 may be related; I'll retry using `npm` instead of `yarn` and report back.

### Attachments

Full [debug.log](https://github.com/jaredly/reason-language-server/files/3189469/debug.log)

**Comment by jwhitley** [comment]
#### More notes
1. I have confirmed that #126 IS NOT the issue: I can repro this problem with both npm and yarn.
2. A likely smoking gun: I just realized that the first argument in that command line is bad, suggesting a quoting or other command line construction problem:
    ```
    '<path_to>/reason-vscode-test/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3'
    ```
    Note that the first argument actually has the command and the first two arguments baked into it, per the displayed quoting.

**Comment by IwanKaramazow** [comment]
@jwhitley https://github.com/jaredly/reason-language-server/pull/281 has addressed this problem and was merged just yesterday.

@jaredly would it be possible to make a new release to the vscode marketplace?

**Comment by jaredly** [comment]
released!

**Comment by jwhitley** [comment]
Thanks @jaredly! Verified as fixed on my end.
