### ISSUE TITLE
[windows] [vscode] RLS won't start

### ISSUE THREAD

**Issue by bgoscinski** [jaredly/reason-language-server#284]
1. as admin in powershell

```
git clone https://github.com/esy-ocaml/hello-reason.git
code ./hello-reason # launch VSCode
```

2. in VSCode open `lib/Util.re` and get `Couldn't get opam switch prefix` error

<details> 
  <summary>node_modules/.lsp/debug.log</summary>
<pre>
Hello - from c:\Users\ja\.vscode\extensions\jaredly.reason-vscode-1.6.0\bin.native.exe.hot.exe
Previous log location: C:\Users\ja\AppData\Local\Temp\lsp.log
Sending notification {"jsonrpc": "2.0", "method": "client/registerCapability", "params": {"registrations": [{"id": "watching", "method": "workspace/didChangeWatchedFiles", "registerOptions": {"watchers": [{"globPattern": "**/bsconfig.json", "globPattern": "**/.merlin"}]}}]}}
Sending response {"id": 0, "jsonrpc": "2.0", "result": {"capabilities": {"textDocumentSync": 1, "hoverProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": ["."]}, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "typeDefinitionProvider": true, "referencesProvider": true, "documentSymbolProvider": true, "codeActionProvider": true, "executeCommandProvider": {"commands": ["reason-language-server.add_to_interface_inner"]}, "codeLensProvider": {"resolveProvider": true}, "documentHighlightProvider": true, "documentRangeFormattingProvider": true, "documentFormattingProvider": true, "documentFormattingProvider": true, "renameProvider": true}}}
Read message 
{"jsonrpc":"2.0","method":"initialized","params":{}}
Read message 
{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"reason_language_server":{"location":"","build_system_override_by_root":{},"refmt":"","lispRefmt":"","format_width":80,"per_value_codelens":false,"dependencies_codelens":true,"opens_codelens":true,"show_module_path_on_hover":true,"reloadOnChange":false,"show_debug_errors":false,"autoRebuild":true,"useOldDuneProcess":true}}}}
Read message 
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re","languageId":"reason","version":1,"text":"let hello = () =>\n  Pastel.(\n    <Pastel>\n      <Pastel color=Red> \"Hello\" </Pastel>\n      \", \"\n      <Pastel color=Green> \"World\" </Pastel>\n      \"!\"\n    </Pastel>\n  );\n"}}}
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Sending notification {"jsonrpc": "2.0", "method": "window/showMessage", "params": {"type": 1, "message": "Couldn't get opam switch prefix"}}
Read message 
{"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/documentSymbol
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Sending response {"id": 1, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Couldn't get opam switch prefix"}}
Read message 
{"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[]}}}
[server] Got a method textDocument/codeAction
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Sending response {"id": 2, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Couldn't get opam switch prefix"}}
Read message 
{"jsonrpc":"2.0","id":3,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/codeLens
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Sending response {"id": 3, "jsonrpc": "2.0", "result": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "command": {"title": "Unable to load compilation data: Couldn't get opam switch prefix", "command": ""}}]}
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
</pre>
</details>

3. close VSCode and in powershell:
```
cd hello-reason
esy install
code .
```

4. in VSCode open `lib/Util.re` and get `Unable to read C:\Users\ja\dev\hello-reason\lib\.merlin` error

<details> 
  <summary>node_modules/.lsp/debug.log</summary>
<pre>
Hello - from c:\Users\ja\.vscode\extensions\jaredly.reason-vscode-1.6.0\bin.native.exe.hot.exe
Previous log location: C:\Users\ja\AppData\Local\Temp\lsp.log
Sending notification {"jsonrpc": "2.0", "method": "client/registerCapability", "params": {"registrations": [{"id": "watching", "method": "workspace/didChangeWatchedFiles", "registerOptions": {"watchers": [{"globPattern": "**/bsconfig.json", "globPattern": "**/.merlin"}]}}]}}
Sending response {"id": 0, "jsonrpc": "2.0", "result": {"capabilities": {"textDocumentSync": 1, "hoverProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": ["."]}, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "typeDefinitionProvider": true, "referencesProvider": true, "documentSymbolProvider": true, "codeActionProvider": true, "executeCommandProvider": {"commands": ["reason-language-server.add_to_interface_inner"]}, "codeLensProvider": {"resolveProvider": true}, "documentHighlightProvider": true, "documentRangeFormattingProvider": true, "documentFormattingProvider": true, "documentFormattingProvider": true, "renameProvider": true}}}
Read message 
{"jsonrpc":"2.0","method":"initialized","params":{}}
Read message 
{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"reason_language_server":{"location":"","build_system_override_by_root":{},"refmt":"","lispRefmt":"","format_width":80,"per_value_codelens":false,"dependencies_codelens":true,"opens_codelens":true,"show_module_path_on_hover":true,"reloadOnChange":false,"show_debug_errors":false,"autoRebuild":true,"useOldDuneProcess":true}}}}
Read message 
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re","languageId":"reason","version":1,"text":"let hello = () =>\n  Pastel.(\n    <Pastel>\n      <Pastel color=Red> \"Hello\" </Pastel>\n      \", \"\n      <Pastel color=Green> \"World\" </Pastel>\n      \"!\"\n    </Pastel>\n  );\n"}}}
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending notification {"jsonrpc": "2.0", "method": "window/showMessage", "params": {"type": 1, "message": "Unable to read C:\\Users\\ja\\dev\\hello-reason\\lib\\.merlin"}}
Read message 
{"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/documentSymbol
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending response {"id": 1, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Unable to read C:\\Users\\ja\\dev\\hello-reason\\lib\\.merlin"}}
Read message 
{"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[]}}}
[server] Got a method textDocument/codeAction
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending response {"id": 2, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Unable to read C:\\Users\\ja\\dev\\hello-reason\\lib\\.merlin"}}
Read message 
{"jsonrpc":"2.0","id":3,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/codeLens
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending response {"id": 3, "jsonrpc": "2.0", "result": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "command": {"title": "Unable to load compilation data: Unable to read C:\\Users\\ja\\dev\\hello-reason\\lib\\.merlin", "command": ""}}]}
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Read message 
{"jsonrpc":"2.0","id":4,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/codeLens
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending response {"id": 4, "jsonrpc": "2.0", "result": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "command": {"title": "Unable to load compilation data: Unable to read C:\\Users\\ja\\dev\\hello-reason\\lib\\.merlin", "command": ""}}]}
</pre>
</details>

5. create empty `lib/.merlin` file and restart VSCode, open lib/Util.re
6. get 2 errors:

```
The Reason Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

```
Unix.Unix_error(12, "mkdir", "C:\\Users\\ja\\dev\\hello-reason\\..\\c:/Users")Raised by primitive operation at file "util/Files.re", line 195, characters 4-27
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "util/Files.re", line 194, characters 4-18
Called from file "src/analyze/Packages.re", line 295, characters 2-30
Called from file "src/analyze/Packages.re", line 561, characters 24-75
Called from file "src/lsp/NotificationHandlers.re", line 74, characters 24-75
Called from file "src/lsp/BasicServer.re", line 84, characters 11-35
```

<details> 
  <summary>node_modules/.lsp/debug.log</summary>
<pre>
Hello - from c:\Users\ja\.vscode\extensions\jaredly.reason-vscode-1.6.0\bin.native.exe.hot.exe
Previous log location: C:\Users\ja\AppData\Local\Temp\lsp.log
Sending notification {"jsonrpc": "2.0", "method": "client/registerCapability", "params": {"registrations": [{"id": "watching", "method": "workspace/didChangeWatchedFiles", "registerOptions": {"watchers": [{"globPattern": "**/bsconfig.json", "globPattern": "**/.merlin"}]}}]}}
Sending response {"id": 0, "jsonrpc": "2.0", "result": {"capabilities": {"textDocumentSync": 1, "hoverProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": ["."]}, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "typeDefinitionProvider": true, "referencesProvider": true, "documentSymbolProvider": true, "codeActionProvider": true, "executeCommandProvider": {"commands": ["reason-language-server.add_to_interface_inner"]}, "codeLensProvider": {"resolveProvider": true}, "documentHighlightProvider": true, "documentRangeFormattingProvider": true, "documentFormattingProvider": true, "documentFormattingProvider": true, "renameProvider": true}}}
Read message 
{"jsonrpc":"2.0","method":"initialized","params":{}}
Read message 
{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"reason_language_server":{"location":"","build_system_override_by_root":{},"refmt":"","lispRefmt":"","format_width":80,"per_value_codelens":false,"dependencies_codelens":true,"opens_codelens":true,"show_module_path_on_hover":true,"reloadOnChange":false,"show_debug_errors":false,"autoRebuild":true,"useOldDuneProcess":true}}}}
Read message 
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re","languageId":"reason","version":1,"text":"let hello = () =>\n  Pastel.(\n    <Pastel>\n      <Pastel color=Red> \"Hello\" </Pastel>\n      \", \"\n      <Pastel color=Green> \"World\" </Pastel>\n      \"!\"\n    </Pastel>\n  );\n"}}}
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
Sending notification {"jsonrpc": "2.0", "method": "window/showMessage", "params": {"type": 1, "message": "Unix.Unix_error(12, \"mkdir\", \"C:\\\\Users\\\\ja\\\\dev\\\\hello-reason\\\\..\\\\c:/Users\")Raised by primitive operation at file \"util/Files.re\", line 195, characters 4-27\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"util/Files.re\", line 194, characters 4-18\nCalled from file \"src/analyze/Packages.re\", line 295, characters 2-30\nCalled from file \"src/analyze/Packages.re\", line 561, characters 24-75\nCalled from file \"src/lsp/NotificationHandlers.re\", line 74, characters 24-75\nCalled from file \"src/lsp/BasicServer.re\", line 84, characters 11-35\n"}}
Read message 
{"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/Users/ja/dev/hello-reason/lib/Util.re"}}}
[server] Got a method textDocument/documentSymbol
[server] processing took 0.ms
Found a `dune` file at C:\Users\ja\dev\hello-reason\lib
]] Making a new jbuilder package at C:\Users\ja\dev\hello-reason\lib
=== Project root: C:\Users\ja\dev\hello-reason
Detected `esy` dependency manager for local use
</pre>
</details>

7. give up and create this ticket 😄 

OS: Windows 10 Home
esy@0.5.7
bs-platform@5.0.4
VSCode@1.34.0
reason-vscode@1.6.0

**Comment by jaredly** [comment]
just to verify -- you're not using WLS, right?

**Comment by bgoscinski** [comment]
I have it installed but I'm not using it

**Comment by bgoscinski** [comment]
@jaredly I think I know what causes the issue. But I don't know how to fix it. Here's what I done:
I cloned RLS repo and built it. Had the same error. Then applied this diff:

```diff
diff --git a/src/analyze/BuildSystem.re b/src/analyze/BuildSystem.re
index e11fe52..18688ed 100644
--- a/src/analyze/BuildSystem.re
+++ b/src/analyze/BuildSystem.re
@@ -177,7 +177,13 @@ let getEsyCompiledBase = () => {
             Json.get("cur__original_root", json) |?> Json.string,
             Json.get("cur__target_dir", json) |?> Json.string,
           ) {
-          | (Some(projectRoot), Some(targetDir)) => Ok(Files.relpath(projectRoot, targetDir))
+          | (Some(projectRoot), Some(targetDir)) =>
+            Log.log("######################### GOT IT #######################");
+            Log.log("projectRoot: " ++ projectRoot);
+            Log.log("targetDir: " ++ targetDir);
+            let result = Files.relpath(projectRoot, targetDir);
+            Log.log("result: " ++ result);
+            Ok(result)
           | _ => Error("Couldn't find Esy target directory (missing json entries)")
           }
         )
```

and this is what appeared in `debug.log`:
```
######################### GOT IT #######################
projectRoot: C:/Users/ja/dev/hello-reason
targetDir: c:/Users/ja/dev/hello-reason/_esy/default/store/b/hello_reason-59fc3058
result: ..\c:/Users/ja/dev/hello-reason/_esy/default/store/b/hello_reason-59fc3058
```
I expected result to be `./_esy/default/store/b/hello_reason-59fc3058` so I dug deeper into `Files.relpath`. I found there something which looks like bunch of tests so I added some which should cover what happens in my case **BUT** there's a catch - I don't know how to run them :P 

```diff
diff --git a/util/Files.re b/util/Files.re
index 3e76d30..56f5de1 100644
--- a/util/Files.re
+++ b/util/Files.re
@@ -23,6 +23,17 @@ let sliceToEnd = (str, pos) => String.sub(str, pos, String.length(str) - pos);
   (("/a/b/c", "/a/b/d/e"), "../d/e"),
   (("/a/b/c", "/d/e/f"), "../../../d/e/f"),
   (("/a/b/c", "/a/b/c/d/e"), "./d/e"),
+
+  (("C:/a/b/c", "C:/a/b/d"), "../d"),
+  (("C:/a/b/c", "C:/a/b/d/e"), "../d/e"),
+  (("C:/a/b/c", "C:/d/e/f"), "../../../d/e/f"),
+  (("C:/a/b/c", "C:/a/b/c/d/e"), "./d/e"),
+
+  /* windows paths are case insensitive */
+  (("C:/a/b/c", "c:/a/B/d"), "../d"),
+  (("C:/a/b/c", "c:/a/B/d/e"), "../d/e"),
+  (("C:/a/b/c", "c:/D/e/f"), "../../../D/e/f"),
+  (("C:/a/b/c", "c:/a/b/C/d/e"), "./d/e"),
 ]]
 let relpath = (base, path) => {
   if (startsWith(path, base)) {
```

Also I'm not even sure if it's worth to maintain `relpath` implementation here. Do you have any suggestions how to proceed?

**Comment by jaredly** [comment]
ooh perfect, thanks! yes, it makes sense that would break it. I think extending relpath is the right way to go.

**Comment by bgoscinski** [comment]
@jaredly How do I run `relpath` tests? Is there some equivalent of `jest --watch`?

**Comment by zetashift** [comment]
Should a PR be made? Currently running into the same issue

**Comment by bgoscinski** [comment]
I'm not working on this

**Comment by remithomas** [comment]
Any updates on this @bgoscinski, if you need help ?

**Comment by bgoscinski** [comment]
@remithomas Feel free to work on this on if you want. I didn't have time yet

**Comment by jaredly** [comment]
I've modified `relpath` to be case-insensitive on windows and macos, so I think this will be fixed? I'm not in a position to verify at the moment unfortunately

**Comment by bgoscinski** [comment]
@jaredly 
The good news is that I just checked and this issue is gone! Thank you 😄 👍
The bad news is that I just checked and _this_ issue is gone. Now it spits out 

```
Invalid response for esy -q sh -c 'echo $OCAMLLIB'

$OCAMLLIB': -c: line 0: unexpected EOF while looking for matching `''
$OCAMLLIB': -c: line 1: syntax error: unexpected end of file
```

When I try to manually run `esy -q sh -c 'echo $OCAMLLIB'` in

1. `powershell` without elevation: 
```
PS C:\Users\ja\dev\hello-reason> esy -q sh -c 'echo $OCAMLLIB'
ERROR: Unable to create symlinks. Missing SeCreateSymbolicLinkPrivilege.

Esy must be ran as an administrator on Windows, because it uses symbolic links.
Open an elevated command shell by right-clicking and selecting 'Run as administrator', and try esy again.

For more info, see https://github.com/esy/esy/issues/389
```
2. `powershell` as admin: 
```
PS C:\Users\ja\dev\hello-reason>  esy -q sh -c 'echo $OCAMLLIB'
C:/Users/ja/.esy/3_/i/ocaml-4.6.10-7ba95816/lib/ocaml
```
3. `bash` (from git for windows) (with and without elevation):
```
ja@blaszak MINGW64 ~/dev/hello-reason (master)
$ esy -q sh -c 'echo $OCAMLLIB'
/c/Users/ja/AppData/Roaming/npm/esy: line 1: /node_modules/esy/_build/default/bin/esy.exe: No such file or directory
```

**Comment by zetashift** [comment]
I get the same thing as @bgoscinski, I'm not sure if this is a reason-language-server issue or esy issue though.

**Comment by bgoscinski** [comment]
I created #319 for this $OCAMLLIB thing
