### ISSUE TITLE
[macos] Error while running preprocessor

### ISSUE THREAD

**Issue by gogocurtis** [jaredly/reason-language-server#285]
Please include steps needed to reproduce the bug, along any relevant sections of the log file, located at `node_modules/.lsp/debug.log`

Followed reason guide and recommendations.
  "devDependencies": {
    "bs-platform": "^5.0.4"
  }

<img width="749" alt="Screen Shot 2019-05-17 at 12 51 52 PM" src="https://user-images.githubusercontent.com/22035299/57952787-1216d780-78a3-11e9-8be4-6aa383dc84ed.png">

.merlin gens path "FLG -ppx /Users/curtis/.nvm/versions/node/v10.9.0/lib/node_modules/bs-platform/lib/bsppx.exe"

:( no work

**Comment by IwanKaramazow** [comment]
@gogocurtis can you update the vscode extension, latest release fixes the problem

**Comment by jaredly** [comment]
Fixed in the latest release :)
