### ISSUE TITLE
Unbound module Lib in example-esy-dune-project

### ISSUE THREAD

**Issue by jchavarri** [jaredly/reason-language-server#286]
- Version: 1.6.1.

I found a simple repro by just slightly changing one of the examples that are already part of the `examples/` folder.

## Repro:

1. Delete `examples/example-esy-dune-project/lib/Awesome.rei`
2. Change the file `examples/example-esy-dune-project/lib/dune`:

```diff
 (library 
  (name lib)
-  (modules_without_implementation awesome))
+)
```

3. Run `esy`
4. Open any `.re` file in `examples/example-esy-dune-project/lib` or `examples/example-esy-dune-project/bin` to see the error `Unbound module Lib`.

## Debug log

```
➡️ running bsc /Users/javi/.esy/3____________________________________________________________________/i/ocaml-4.6.10-1dc037cc/bin/ocamlc.opt -c -I '/Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/_esy/default/store/b/hello-bb5af4c3/default/bin/.Hello.eobjs/byte' -I '/Users/javi/.esy/3____________________________________________________________________/i/ocaml-4.6.10-1dc037cc/lib/ocaml' -bin-annot -w -40 -impl /Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/_esy/default/store/b/hello-bb5af4c3/.lsp/Hello.ast with pwd /Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/bin
Now loading /Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/_esy/default/store/b/hello-bb5af4c3/.lsp/Hello.cmt
Size 2138
<< Making lastDefinitions with type error for file:///Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/bin/Hello.re
Sending response {"id": 1, "jsonrpc": "2.0", "result": null}
Running diagnostics for file:///Users/javi/Development/github/reason-language-server/examples/example-esy-dune-project/bin/Hello.re
type error here File "", line 2, characters 5-8:
Error: Unbound module Lib
```

**Comment by pjhenning** [comment]
I'm also running into this with the reason 'hello world' example project for esy: https://github.com/esy-ocaml/hello-reason

**Comment by pjhenning** [comment]
Update: setting `useOldDuneProcess: false` in the vs code extension settings as per https://github.com/jaredly/reason-language-server/issues/105#issuecomment-482760642 made this issue go away, perhaps this step should be documented somewhere more obvious. I'll submit a PR some time this week if I get a chance.

**Comment by jchavarri** [comment]
As @pjhenning mentioned, I can't repro with the new `useOldDuneProcess` flag set to `false`. 🤷‍♂ 

Closing then! Thanks @jaredly for this fix 👏
