### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by GabrielDuarteM** [jaredly/reason-language-server#29]
I'm having some errors when running the server not sure if it's the extensions fault though, as I'm installing this to learn the language. I've installed the latest beta version (1.0.0-beta.2), and when I open a reason file, I get the following on the `Reason Language Server` output tab:
```
[Error - 21:54:20] Connection to server is erroring. Shutting down server.
[Error - 21:54:20] Connection to server is erroring. Shutting down server.
Setting log location: d%3A\Users\gabri\Documents\Projetos\reason\my-first-app\node_modules\.lsp\debug.log
```

To reproduce: 
1. Install the vsix extension
2. Run `yarn add bs-platform `
3. Run `yarn bsb -init my-first-app -theme basic-reason`
4. Start code on the `my-first-app` folder

I've noticed too that the extension appears to be creating a weird directory tree `d%3A\Users\gabri\Documents\Projetos\reason\my-first-app\node_modules\.lsp\debug.log` (`d%3A` is a folder, and probably should be `d:\`). The contents of the log file is this:

```
Sending response {"id": 0, "jsonrpc": "2.0", "error": "No bsconfig.json found"}
Finished
```

I'm using Windows 10, vscode 1.24.1, node v10.3.0 and yarn 1.7.0

Am I doing something wrong?

**Comment by jaredly** [comment]
ah yes, I don't support drives other than `C:` yet 😛 I'll fix that directly

**Comment by GabrielDuarteM** [comment]
hahahah yeah, i tested on the `C:` drive and it worked fine. Unfortunately, i can't keep projects on that drive (its a small SSD), so I can help with that if you want

**Comment by jaredly** [comment]
Fixed! https://github.com/jaredly/reason-language-server/releases/tag/1.0.0-beta.4
