### ISSUE TITLE
Windows issue with single quoted -ppx

### ISSUE THREAD

**Issue by goodcodedev** [jaredly/reason-language-server#292]
When using jsx, bsb output something like
`FLG -ppx 'C:\...\node_modules\bs-platform\lib\bsppx.exe -bs-jsx 2'`
to .merlin file.
On windows, this can lead to an error like `bsc.exe: wrong argument '2''; option '-bs-jsx' expects an integer`.

This is more probably something that can be changed in bsb, but to get things working and _possibly_ more robust, the case can be handled in reason-language-server.

I made a quick hack to get this working in src/analyze/Packages.re (the branch of os_type == "Win32"):
```rust
let escapePreprocessingFlags = flag => {
  /* ppx escaping not supported on windows yet */
  if (Sys.os_type == "Win32") {
    /* Quick fix for single quoted ppx flag outputted by bsb to .merlin file */
    let length = String.length(flag);
    if (length > 6 && String.sub(flag, 0, 6) == "-ppx '") {
      "-ppx \"" ++ String.sub(flag, 6, length - 7) ++ "\"";
    } else {
      flag;
    }
  } else {
    let parts = Utils.split_on_char(' ', flag);
    switch(parts) {
      | [("-ppx" | "-pp") as flag, ...rest] =>
        flag ++ " " ++ Utils.maybeQuoteFilename(String.concat(" ", rest))
      | _ => flag
    }
  }
};
```
Though I haven't worked out certainty for the cases to handle.

**Comment by deklanw** [comment]
Just installed Reason for the first time to try it out... and this is the first thing I see :\

**Comment by goodcodedev** [comment]
Should be fixed in this release: https://reasonml.chat/t/call-for-testing-for-beta-release-of-bs-platform-5-0-5-beta-1/1712 (using double quotes)
