### ISSUE TITLE
the generation of `bin.exe` for developing?

### ISSUE THREAD

**Issue by Huxpro** [jaredly/reason-language-server#298]
Reproduce step: 
following the `contributing` and `debug` part of `README`

Behaviour:
1. Reason LS works well in the `[Extension Development Host]`, i.e. client-side.
2. But for the server side, i.e., the source code of this repo, it throws `Reason Language Server not found! You specified ~/reason/reason-language-server/bin.exe`.

This is expected since the location is hardcoded in the `.vscode/config.json`:

```json
"reason_language_server.location": "./bin.exe",
```

I `grep` and found several scripts inside `package.json` related to that, but not sure what's the exact order to invoke them. 

Can we make the generation of `bin.exe` part of `esy` build process to make the DX better?

**Comment by mrmurphy** [comment]
Is there a workaround for this in the meantime? NewBs like me don't even know how to get bin.exe generated in the first place, or where to point the language server extension when developing on it.

**Comment by mrmurphy** [comment]
Or just an update to the readme, @jaredly ?

**Comment by mrmurphy** [comment]
Thanks to @thangngoc89 I realized I was just missing the "symlink" step :octocat: .
