### ISSUE TITLE
re in markdown code block

### ISSUE THREAD

**Issue by Huxpro** [jaredly/reason-language-server#299]
<img width="1003" alt="Screen Shot 2019-06-09 at 10 14 30 PM" src="https://user-images.githubusercontent.com/5563315/59173942-15009300-8b04-11e9-861f-b6cc8caf3d99.png">

I was trying to add `re` into the markdown embedded code block for Reason but found it's occupied by `regex_python`. 

I am not sure if this is injected by some third-party extensions or built-in. But Is there anyway we can override this?

**Comment by Huxpro** [comment]
Imaging we could have a dropdown menu in configuration to choose what language to use in fenced code block:

```
<Select name="re">
  <Item> regex-python (from Markdown Basics) </Item>
  <Item> reason (from Reason Language Server) </Item>
</Select>
```

**Comment by Huxpro** [comment]
Okay. It turns out that we can inject the grammar at higher level to override `re` for us directly. 
See: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/commit/e333677e840fd28f382935650553736aaebc2207

The question now is do we want to override it?

**Comment by jaredly** [comment]
I'm definitely on board with overriding it 👍
