### ISSUE TITLE
Funny output escaping issue

### ISSUE THREAD

**Issue by chenglou** [jaredly/reason-language-server#33]
In the 1.0.0-beta.3:
<img width="341" alt="screenshot 2018-06-23 13 37 59" src="https://user-images.githubusercontent.com/1909539/41813428-e6e8a9c2-76ea-11e8-81c2-5f64ea1a66f2.png">

Repro:

```reason
module General = {
  type tree('a) =
    | Leaf('a)
    | Branch(children('a))
  and children('a) = list(tree('a));
  let leaf = data => Leaf(data);
  let branch = children => Branch(children);
};
```

Hover over `| Leaf`

**Comment by jaredly** [comment]
thanks for reporting, fixed
