### ISSUE TITLE
Error: Unbound module when creating project with pesy@0.5.0-alpha.6

### ISSUE THREAD

**Issue by Faliszek** [jaredly/reason-language-server#332]
System: macOS Mojave 10.14.6
Editor: Vscode
Link to repo: https://github.com/Faliszek/vscode-pesy-repro
Debug log: In repo

**Steps to reproduce**
```
npm remove -g pesy && npm install -g pesy@0.5.0-alpha.6
mkdir my-project && cd my-project
pesy
```

After creating project with pesy@0.5.0-alpha.6, in this version declaring imports in dune file are slightly changes. 
And on all files Vscode return error:

```
File "command line", line 1:
Error: Unbound module VscodeReproPesyLibraryPesyModules
```

The dune file looks like this:
```
(library (name VscodeReproPesyLibrary)
    (public_name vscode-repro-pesy.library)
    (modules (:standard \ VscodeReproPesyLibraryPesyModules))
    (libraries vscode-repro-pesy.library.pesy-modules)
    (flags -open VscodeReproPesyLibraryPesyModules))
(library (public_name vscode-repro-pesy.library.pesy-modules)
    (name VscodeReproPesyLibraryPesyModules)
    (modules VscodeReproPesyLibraryPesyModules)
    (libraries console.lib pastel.lib))
(rule
    (with-stdout-to VscodeReproPesyLibraryPesyModules.re
        (run echo  "module Console = Console;\
                  \nmodule Pastel = Pastel;")))
```
I also create other project, with `pesy@0.4.4`
 ```
npm remove -g pesy && npm install -g pesy
mkdir old-pesy && cd old-pesy
pesy
```
and dune file look like this, and the error is gone
```
; !!!! This dune file is generated from the package.json file by pesy. If you modify it by hand
; !!!! your changes will be undone! Instead, edit the package.json and then rerun 'esy pesy' at the project root.
; !!!! If you want to stop using pesy and manage this file by hand, change package.json's 'esy.build' command to: refmterr dune build -p  old-pesy
(library
   ; The namespace that other packages/libraries will access this library through
   (name OldPesy)
   ; Other libraries list this name in their package.json 'require' field to use this library.
   (public_name old-pesy.lib)
)
```

**Comment by jordwalke** [comment]
I suggested filing an issue in this repo, because we tried to reproduce with "Ocaml and Reason IDE" and could not.

Let us know if there's something easy we could change with how pesy outputs its dune config (note, this is the preview version of pesy that bring npm like require aliases). There were no reports of reason-vscode working incorrectly with the previous versions of pesy, but we think that the new require style feature is pretty compelling. (Please check it out if you're interested).

**Comment by jordwalke** [comment]
I wonder if this is related to `buildsInSource`. The project leaves the field empty which means that it will not build in source, and will not build in the _build directory but will build completely out of source into the directory given by `esy echo '#{self.target_dir}'`

**Comment by prometheansacrifice** [comment]
This is issue is not present on Linux it looks like - tried it earlier on an Arch Linux machine.

**Comment by Faliszek** [comment]
I upgraded reason-vscode extension to 1.7.2, and error is gone even with new pesy import approach.
I think that this issue can be closed. Thanks for all your work @jaredly !
