### ISSUE TITLE
[Suggestion] Remove error location from the error message in problem panel

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#37]
For example:

![image](https://user-images.githubusercontent.com/3049054/42100131-95f29b46-7be9-11e8-94ef-cd1b94913cbb.png)

The error location shouldn't be in the message, I find it really annoying and take a lot of space. I can just click on the error message and VS Code jumps to the right location

**Comment by jaredly** [comment]
oh good call

**Comment by jaredly** [comment]
![image](https://user-images.githubusercontent.com/112170/42128367-0444ec66-7c67-11e8-9f18-6055db6c6064.png)
ok, made it much less noisy

**Comment by wegry** [comment]
@jaredly could this characters in the warning also include the range? In your screencap above, it might look like `(87, 24-28)`?

**Comment by jaredly** [comment]
I think those numbers are provided by vscode, don't think I have control over that
