### ISSUE TITLE
VS Code underlines only the first line for errors

### ISSUE THREAD

**Issue by nenofite** [jaredly/reason-language-server#371]
I'm using the VS Code plugin in an Esy project using Dune as a build system. When I edit ReasonML files, any errors are highlighted as if they are part of the first word in the file, rather than on the line they occur:

![image](https://user-images.githubusercontent.com/1776160/71296466-95fed980-2334-11ea-8b14-4299d42d3661.png)

Hover shows the correct line:
![image](https://user-images.githubusercontent.com/1776160/71296477-9c8d5100-2334-11ea-9774-603ec734949e.png)

When I edit OCaml files, the error highlighting works correctly. This bug only seems to occur for ReasonML files.

I created a minimal example project which exhibits this bug: https://github.com/nenofite/reason-language-server-bug-example

Load the file `lib/Lib.re` in VS Code to see the bug.

Here is the debug log:
[debug.log](https://github.com/jaredly/reason-language-server/files/3990530/debug.log)

**Comment by nenofite** [comment]
In case it's helpful, the extension is reason-vscode version 1.7.4!

**Comment by jaredly** [comment]
I was just noticing this too 🤔

**Comment by jaredly** [comment]
I think this is limited to 4.08
