### ISSUE TITLE
reason-language-server does not work when used with code snap package

### ISSUE THREAD

**Issue by abate** [jaredly/reason-language-server#372]
I've tried for quite a while, but I didn't manage to get this work.

`sudo snap install code --classic`

then install the vscode pluging and specify the `reason-language-server` location in
the config.

Now doesn't matter what I trie I get : 
```Failure("Must have a rootUri")Raised at file "stdlib.ml", line 29, characters 17-33 Called from file "util/Infix.re" (inlined), line 9, characters 42-53 Called from file "src/lsp/Main.re", line 47, characters 12-80 Called from file "src/lsp/BasicServer.re", line 130, characters 13-38```

and clearly 
```[Error - 1:54:36 PM] Connection to server is erroring. Shutting down server.```

I really don't understand what's going on. Is this a stupid conf mistake on my side or an
issue with this combo ?

my project is a simple reason-react project using yarn.

**Comment by jaredly** [comment]
`Must have a rootUri` means that the "initialization" message sent by your lsp client doesn't contain the `rootUri` field, which is required. What version of vscode are you using?

**Comment by abate** [comment]
```
$ snap list 
Name           Version    Rev   Tracking     Publisher   Notes
code           26076a4d   23    stable       vscode✓     classic
```

**Comment by jaredly** [comment]
Weird. Could you paste in the contents of `node_modules/.lsp/debug.log`?

**Comment by abate** [comment]
I tried again. I've noticed this problem arise when I open a file directly calling `code app/src/index.re` but not when I open vscode and then select a project folder. In the first case I get the error ( but not debug.log, I guess it exists too early to create one ) , in the second case everything works as expected.

So apparently vscode does not pass the `rootUri` when invoked with a file directly.

**Comment by jaredly** [comment]
ah I guess that makes sense.

**Comment by jaredly** [comment]
thinking about this a little more, i think we could get away with making the rootUri optional
