### ISSUE TITLE
command 'reason-language-server.restart' not found

### ISSUE THREAD

**Issue by arecvlohe** [jaredly/reason-language-server#373]
Thanks for reason-language-server! It has made developing in reason so much more productive with all the editor integrations. 

Up to this point I have had no issues using RLS in vscode. The issue that I am facing is that RLS is not working. When I try and restart RLS (with cmd + P) I get this error: `command 'reason-language-server.restart' not found`. I tried trouble shooting by uninstalling and reinstalling reason-vscode. This did not work. I looked at the docs and saw:

> If that doesn't work, try cleaning built artifacts, with bsb -clean-world (or for dune, dune clean). Then try to build, with bsb -make-world (or dune build @install) and see if that works.

I attempted to do this as well but this did not work either. I am wondering if I have a much larger issue that I am not seeing. Any help would be appreciated.

**Comment by arecvlohe** [comment]
Down graded to 1.7.3. I think something is wrong with the latest version but I couldn't tell you what.

**Comment by vasco3** [comment]
I have the same issue...

**Comment by romanschejbal** [comment]
Re-open this issue then?

**Comment by vasco3** [comment]
I stopped having the issue.. I'm in the latest

**Comment by atikatantiya** [comment]
I have the same issue.
