### ISSUE TITLE
Error while building on Linux

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#38]
I'm using Ubuntu 18.04 and this is what I got while trying to compile this project:

Reproduce:

- Clone, yarn install
- yarn build
- Log: https://gist.github.com/thangngoc89/68b42bd3491265cf41fd3ca5044dc459

**Comment by jaredly** [comment]
wow

**Comment by thangngoc89** [comment]
So sorry. I forgot about this. I talked to bsbnative folks and turn out, this is a bug on their end. It’s building now
