### ISSUE TITLE
Extension fails to load on macOS 10.13

### ISSUE THREAD

**Issue by ohana54** [jaredly/reason-language-server#381]
```
[Info  - 9:47:16 PM] Connection to server got closed. Server will restart.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/user/.vscode/extensions/jaredly.reason-vscode-1.7.5/bin.native (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

I'm on macOS version 10.13.4. Reverted to 1.7.4 for now.
I don't know if this should be fixed, since I'm on an old OS version.
Thanks!

**Comment by ng-jim** [comment]
Seems I may have the same problem - reason-vscode-1.7.5 crashes on macOS version 10.11.6
1.74 does work fine, but my team mates will be angry with me if refmt produces different results :(
Yeah, I know, VERY old macOS!
Many thanks!

**Comment by jaredly** [comment]
hmm i wonder what changed that would cause that crash....

**Comment by ng-jim** [comment]
Let me know if I can provide any more information!

**Comment by ng-jim** [comment]
So, without really knowing what I was doing, I followed your build instructions, everything built fine, all tests passed. Then copied the results to my vscode extentions directory ... cp bin.native ~/.vscode/extensions/jaredly.reason-vscode-1.7.5/

It no longer crashes. Yay! Result!

So I'd hazard a guess it might have something to do with the environment you build it on? Did that change recently?

**Comment by ng-jim** [comment]
Ah. I suspect this might be the change in the build?
https://github.com/jaredly/reason-language-server/commit/92b6c210d6281f1d75ffaf37e908b61a95bb626b
