### ISSUE TITLE
reason-vscode + onivim doesn't seem to work in windows

### ISSUE THREAD

**Issue by bikallem** [jaredly/reason-language-server#387]
Not sure if the issue is with onivim or reason-vscode, however, reason-vscode is not working for me on Windows.

Windows 10(OS build 16299.1565)
reason-vscode: 1.7.5

I installed and configured ```reason-vscode``` as specified in https://github.com/jaredly/reason-language-server#onivim, i.e. I have added the following to onivim configuration file,
```
"language.reason.languageServer.command": "c://rls//reason-language-server.exe",
"language.reason.languageServer.arguments": [],
"language.reason.languageServer.configuration": {},
```
I launch oni2 from ```c:\Users\user1\source\proj1``` and try to edit ```.re``` file. 

I get error message as below,

Error message: Reason Language Server not found! c:\Users\user1\source\proj1\c:\Program Files\Onivim2\rls.exe

It seems onivim is trying to look in to a folder which is a appending of current folder + c:\Program Files\Onivim2\rls.exe. Is this reason-vscode issue perhaps?

**Comment by jaredly** [comment]
@bikallem I believe that readme section is out of date -- last I checked oni2 ships with the executable baked in.

**Comment by bikallem** [comment]
yep. it seems the issue is on onivim side. closing this.
