### ISSUE TITLE
RLS freezes when using Neovim

### ISSUE THREAD

**Issue by dylanirlbeck** [jaredly/reason-language-server#398]
So I haven't been able to find the cause of this issue because it happens so sporadically, but from time to time when I'm editing in Neovim the language server just seems to freeze. More specifically, errors may have shown up for a piece of code that I just deleted, but the errors don't leave the screen. Moreover, I seem to lose all the features of RLS (autocomplete, formatting, etc.).

The only solution I've found is to quit Vim entirely, but this is extremely frustrating so I wanted to see if there was any sort of fix. I'm happy to provide more information if necessary. Thanks in advance!

As a follow-up, if there is a way to restart the language server from Neovim, that'd also be a helpful thing to know!

**Comment by cristianoc** [comment]
@dylanirlbeck thanks for the report! Would you add to this issue if you notice anything else when this happens again.
Also, what's the platform, and are there processes going 100% cpu when that happens?

**Comment by dylanirlbeck** [comment]
So I think I've narrowed down the problem a little. For starters, I stopped running `bsb -make-world -w` in another shell window. I saw in the `README` that this causes some weird errors, so maybe this helped.

I think my issue has to do with this error in Vim when I try to do format the text or jump to a definition: `[LC] sending on a disconnected channel`. I solve this by doing `:LanguageClientStop` and then `:LanguageClientStart`, but it's still frustrating since it feels like it happens more than it should.

Finally, I'm running MacOSX, and no processes are going to 100% CPU.

**Comment by dylanirlbeck** [comment]
@cristianoc I'm going to put a gist of my (condensed) `init.vim` below. If you have any time and could take a look to see if anything seems off I'd really appreciate it. RLS continues to die at random points and I've had to switch to VSCode, which is not ideal.

https://gist.github.com/dylanirlbeck/5e1f550b22deec3ceb2fbe6509fd38de

**Comment by dylanirlbeck** [comment]
Temporary solution (I'll confirm if this works consistently and close this issue for now) --- switch to Ale for linting and formatting. See [this](https://www.rockyourcode.com/reason-ml-development-with-vim/) great article.
