### ISSUE TITLE
neovim coc settings not applied

### ISSUE THREAD

**Issue by hesxenon** [jaredly/reason-language-server#402]
Hello, I'm using neovim 0.5.0 with coc 0.0.74 and I've tried to pass `autoRebuild: false` to the language server by putting it into the `settings` object as documented on the coc wiki. Doing so _did_ work until some time ago (didn't really notice until now).

It looks like the settings are passed correctly to the language server from coc according to this statement in the coc log (which should be the same as vscode afaik)

```
[Trace - 8:38:43 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "autoRebuild": false,
        "format_width": 140,
        "per_value_codelens": true,
        "opens_codelens": true
    }
}
```

Following the advice from #201 did not help either. Please advise, kinda stuck here.

**Comment by hesxenon** [comment]
nevermind, moved away from coc to LanguageClient which seems to work better in general

**Comment by alexeygolev** [comment]
For those who landed here searching for the coc fix. Turns out you need to have a `reason_language_server` in your settings. So the configuration should look something like this:

```json
  "languageserver": {
    "reason": {
      "command": "~/lsps/reason-language-server",
      "filetypes": ["reason"],
      "settings": {
        "reason_language_server": {
          "format_width": 100
        }
      }
    }
]
```
