### ISSUE TITLE
Format strips some characters from unicode strings

### ISSUE THREAD

**Issue by PedroHLC** [jaredly/reason-language-server#404]
Only tested in sublime 3211 and reason-language-server 1.7.5 (from AUR), within ArchLinux.

To reproduce, you can save this snippet to a test file and inject it into any project:
```Reason
[@react.component]
let make = () => {
  <div>
      {
        React.string(
          {j| Início não estão disponíveis Página |j}
        ) }
      </div>
};
``` 
After format it produces:
```Reason
[@react.component]
let make = () => {
  <div> {React.string({j| Iníio nã estã disponíeis Páina |j})} </div>;
};
```
Sometimes it strips more than one character...

**Comment by jaredly** [comment]
oh weeeird. @PedroHLC does that also happen when running `refmt` from the command-line?

**Comment by PedroHLC** [comment]
```
╰─λ refmt /tmp/test.re                                                         0 < 09:42:24
[@react.component]
let make = () =>
  <div>
    {React.string({j| Início não estão disponíveis Página |j})}
  </div>;
``` 
No, it doesn't.

**Comment by PedroHLC** [comment]
When using in neovim plugin it generates the same result as `refmt`.
So it may be a sublime's lsp package bug?
