### ISSUE TITLE
Version 1.7.6 not released?

### ISSUE THREAD

**Issue by gaku-sei** [jaredly/reason-language-server#405]
it appears that even though the 1.7.6 version got released (https://github.com/jaredly/reason-language-server/commit/b7a89d919b99c2621fa54b20f52ead71c7669e4d) it's not available in the vscode marketplace 😕

**Comment by jaredly** [comment]
I needed to do some manual testing, sorry for the delay :) it's on the marketplace now

**Comment by gaku-sei** [comment]
I was affraid it could be an issue while deploying, thank you very much @jaredly ☺️
