### ISSUE TITLE
Rename symbol bug with module

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#41]
![screencast-2018-07-02-02_45_46](https://user-images.githubusercontent.com/3049054/42138108-4dd92da6-7da2-11e8-91e0-c18057adf14d.gif)

Reproduce: 

- Start with this code:

```reason
module Foo = {
  let foo = "bar";
};

let baz = Foo.foo;
```

- Rename the foo symbol in `let baz`
- Result: 

```reason
module Foo = {
  let baz = "bar";
};

let baz = baz;
```

- Expected

```reason
module Foo = {
  let baz = "bar";
};

let baz = Foo.baz;
```

**Comment by jaredly** [comment]
ohh good call

**Comment by jaredly** [comment]
fixed
