### ISSUE TITLE
node_modules/bs-platform/lib/bsc.exe: unknown option '-bs-no-builtin-ppx'.

### ISSUE THREAD

**Issue by veggiemonk** [jaredly/reason-language-server#416]
I followed the install instructions and installed the latest of bs-platform: https://reasonml.github.io/reason-react/docs/en/installation
```shell
npm install --global bs-platform
bsb -init my-react-app -theme react-hooks
cd my-react-app && npm install && npm start
# in another tab
npm run server
```

Open VSCode, got the error: `bsc.exe: unknown option '-bs-no-builtin-ppx'.`
The debug log: https://gist.github.com/veggiemonk/ee99b6d1480740755ae5951c5cd8769d

Running OSX 10.15.3

**Comment by veggiemonk** [comment]
```
bs -v
7.1.1
```

Is that related to: https://github.com/jaredly/reason-language-server/pull/413/files

**Comment by Malanius** [comment]
Same for me on Ubuntu 19.10. 

```bash
bsc -v
BuckleScript 7.1.1 ( Using OCaml:4.06.1+BS )
```

Helps to downgrade the extension to 1.7.5 (both 1.7.6 and 1.7.7 have this issue).

**Comment by madeinquant** [comment]
Encounter a same issue when coding reasonml .
bsc.exe: unknown option '-bs-no-builtin-ppx'.
bsc -v
BuckleScript 7.1.1 ( Using OCaml:4.06.1+BS )

**Comment by veggiemonk** [comment]
I thought it was a caching problem with extensions in VSCode so I removed the extension and loaded the VXSi manually. Same error.

**Comment by madeinquant** [comment]
fallback to 1.7.6

**Comment by veggiemonk** [comment]
It is now fixed in https://github.com/jaredly/reason-language-server/releases/tag/1.7.8
