### ISSUE TITLE
Warnings are reported as errors

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#42]
Simple step to produce:

```
let concat = (~first, ~second) => first ++ second;

concat(1, 2);
```

This should produce a warning but VSCode is showing it's an error

**Comment by jaredly** [comment]
What bsb version is this? I've seen this with bsb-native I think

**Comment by thangngoc89** [comment]
@jaredly I'm using bsb 3.1.5

**Comment by jaredly** [comment]
hah that code sample actually has a type error. 
```
let concat = (~first, ~second) => first + second;

concat(1, 2);
```
looks like this is fixed -- lmk if it shows up again
