### ISSUE TITLE
rls errors out with bs-platform 7.2.1

### ISSUE THREAD

**Issue by jwhitley** [jaredly/reason-language-server#420]
In either the vscode or vim (coc-reason) integrations, rls errors out with bs-platform 7.2.1, failing to find one or more relevant bs-platform executables (bsb.exe, refmt, etc.).

Repro steps:
1. Clone https://github.com/jwhitley/a-reason-react-tutorial.git
2. `npm i` or `yarn install`
3. Fire up either VSCode or vim using coc-reason(**).

(**): I've manually updated my local coc-reason install to use rls 1.7.7, since coc-reason is increasingly out of date. See my related pull-request on this repo.

Log snippet from vscode:
```
Sending response {"id": 1, "jsonrpc": "2.0", "error": {"code": -32603, "message": "/Users/whitley/src/a-reason-react-tutorial/node_modules/bs-platform/lib/bsb.exe not found. aborting"}}
```

Log snippet from coc-reason:
```
Sending response {"id": 1, "jsonrpc": "2.0", "result": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "command": {"title": "Failed to refmt '/Users/whitley/src/a-reason-react-tutorial/node_modules/bs-platform/lib/refmt.exe' --print binary --recoverable --parse re > '/Users/whitley/src/a-reason-react-tutorial/node_modules/.lsp/TodoApp.ast'\n/bin/sh: /Users/whitley/src/a-reason-react-tutorial/node_modules/bs-platform/lib/refmt.exe: No such file or directory", "command": ""}}]}
```

In a recent version of bs-platform, the relevant executables have moved, breaking hardcoded paths employed by rls.

I note that `node_modules/.bin/bsrefmt` and `node_modules/.bin/bsb` are correctly linked. It seems like it would be preferable to reference those instead and avoid the whims of internal package reorganizations.

**Comment by bobzhang** [comment]
@jwhitley I tested 1.7.8 which works for me

**Comment by jwhitley** [comment]
@bobzhang awesome, confirmed. I updated PR #410 to update coc-reason to 1.7.8.
