### ISSUE TITLE
Run bsb first in bsb-native project

### ISSUE THREAD

**Issue by chinmayakcv** [jaredly/reason-language-server#43]
I have a bsb-native project with native as backend. I am facing below error in vscode
![Start bsb server first](https://user-images.githubusercontent.com/9429409/42173495-cdb7aca6-7e3c-11e8-8df3-3ecdf6ef95c2.png)

Environment:
 System:
    OS: Linux 4.13 Ubuntu 16.04.4 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.4.1
    npm: 6.1.0 
  Utilities:
    Make: 4.1 - /usr/bin/make
  IDEs:
    VSCode: 1.24.1 - /usr/bin/code

**Comment by jaredly** [comment]
What version of bsb? Also, are you compiling to native, or to bytecode? My
bsb-native support is a little spotty at the moment (different versions
have different places that they put the compiled files...)

**Comment by chinmayakcv** [comment]
I am compiling to bytecode.
```
 "devDependencies": {
    "bs-platform": "bsansouci/bsb-native#2.1.1"
  },
  "dependencies": {
    "minimist.re": "0.0.5",
    "reason-cli-tools": "^1.0.4",
    "rex-json": "^1.4.0"
  }
```

**Comment by chinmayakcv** [comment]
When I am trying to compile to native and restart `restart-language-server` I am facing 

```
Unix.Unix_error(Unix.ENOENT, "opendir", "${PROJECT_ROOT}/node_modules/bs-platform/lib/ocaml/native")Raised by primitive operation at file "/home/awesome/clone/reason-language-server/src/util/Files.re", line 172, characters 7-24
Called from file "/home/awesome/clone/reason-language-server/src/util/FindFiles.re", line 175, characters 17-44
Called from file "/home/awesome/clone/reason-language-server/src/util/FindFiles.re", line 229, characters 24-51
Called from file "/home/awesome/clone/reason-language-server/src/lsp/Main.re", line 93, characters 55-115
Called from file "/home/awesome/clone/reason-language-server/src/util/Result.re", line 10, characters 51-56
Called from file "/home/awesome/clone/reason-language-server/src/lsp/BasicServer.re", line 113, characters 13-38


```

**Comment by jaredly** [comment]
ok, so I pushed a fix to support bsb 2.1.1. I don't think it will support bytecode at the moment though.
I'm still not 100% sure how to support multiple compilation targets 🤔 I might add a config option where you can specify native or bytecode

**Comment by chinmayakcv** [comment]
I updated `bsb-native` to `3.2.0` but couldn't succeed.
```
Parse error:
/bin/sh: 1: ${PROJECT_ROOT}/node_modules/bs-platform/lib/refmt3.exe: not found
```
But it exists in `node_modules`
In VSCode Output
```
[Error - 09:24:23] Request textDocument/codeLens failed.
  Message: Could not get compilation data
  Code: -32603 

```

**Comment by thangngoc89** [comment]
@chinmayakcv this is an error with bsb-native. @bsansouci pushed a fix. You can reinstall bsb-native

**Comment by chinmayakcv** [comment]
@thangngoc89 :+1: 
Removed `node_modules` and reinstalled. That resolved the issue
