### ISSUE TITLE
Use module open args to bsb for autocompletion

### ISSUE THREAD

**Issue by wegry** [jaredly/reason-language-server#44]
Bringing this over from the Discord channel. One thing I was hoping for was that bsc-flags opens might be respected by the language-server?

An example flag would be `-open Belt`. Currently, this flag is ignored, and the ocaml `Array.map` is used instead of `Belt.Array.map`.

**Comment by jaredly** [comment]
good call, will fix

**Comment by wegry** [comment]
At least in the example project, this looks like it currently works with `-open Belt` (and beta 6)?

![screen shot 2018-07-28 at 3 49 15 pm](https://user-images.githubusercontent.com/5156873/43357172-d14b958a-927d-11e8-8048-cd1f4102d1c3.png)

I was a little bit suspicious because of ![screen shot 2018-07-28 at 3 50 52 pm](https://user-images.githubusercontent.com/5156873/43357191-09a49fbc-927e-11e8-89ba-54150cacb5b8.png)

Pervasives' Array.map still seems to be creeping through to autocomplete.

**Comment by jaredly** [comment]
oh cool :) yeah, so autocomplete doesn't currently dedup between things that override each other. I'll make an issue for that
