### ISSUE TITLE
Autocomplete list doesn't show modules

### ISSUE THREAD

**Issue by nim442** [jaredly/reason-language-server#458]
For example, I should be able to see the modules defined in this Webapi module. Once you start typing the module name, it  shows up in the list.
![image](https://user-images.githubusercontent.com/7310201/87620237-08c60c80-c6ec-11ea-8a89-e83bc4910ab6.png)
Last version it was working on was 1.7.8

**Comment by yawaramin** [comment]
Possibly due to #418 ? It's the only related change: https://github.com/jaredly/reason-language-server/compare/1.7.8...1.7.10#diff-961799531ef53f0832744f09dfa75fb1

**Comment by nim442** [comment]
I reverted that change locally and it fixed this issue

**Comment by yawaramin** [comment]
Does it also show any `local_*` module?

**Comment by nim442** [comment]
Yeah, so that change hides all modules. not just the lowercased ones
