### ISSUE TITLE
Vscode bsc error on bs-platform@8.1.1

### ISSUE THREAD

**Issue by DerivedMate** [jaredly/reason-language-server#459]
The extension throws an error on bs-platform@8.1.1 (and 8.1.0)
```
/home/tomasz/Proyectos/reason/test_/node_modules/bs-platform/linux/bsc.exe: unknown option '-c'.
```
![imagen](https://user-images.githubusercontent.com/28303367/87781075-459b1c00-c830-11ea-9a70-ef62468a6df4.png)

how to recreate:
1. Create a new project `bsb -init project -theme basic-reason`
2. `cd project`
3. `npm i -D`
4. open the project with code

note: the project compiles well using `bsb -w`

versions:
- code: 1.47.1
- bsc: BuckleScript 8.1.1 ( Using OCaml:4.06.1+BS )
- reason-vscode: 1.7.10

**Comment by DerivedMate** [comment]
I guess that the debug log might come in handy 
[debug.log](https://github.com/jaredly/reason-language-server/files/4937519/debug.log)

**Comment by farukg** [comment]
Hi,

the linked issue #460 is not related to this issue but is referenced (some kind of github bug?). I just wanted to mention so that it is clear that this issue is not addressed yet.

**Comment by DerivedMate** [comment]
Hi,
yes, it must be a github bug of sorts

**Comment by jaredly** [comment]
But 8.0 works? Interestingly, I don't see 8.1 mentioned in the changelog https://github.com/BuckleScript/bucklescript/blob/master/Changes.md 🤔

**Comment by DerivedMate** [comment]
Yes, 8.0(.3) works. The '-c' option appears to have been deleted in this  [commit](https://github.com/BuckleScript/bucklescript/commit/c7574e3625f34d977ca5329922c7284e0e8952b2) as a part of a cleanup (dunno who, though).
I've also just testes it on 8.2.0-dev.1 (extension 1.7.11), and it now crushes on a new error:
![imagen](https://user-images.githubusercontent.com/28303367/89125490-2a423900-d4df-11ea-983a-20204ce1e518.png)

Here are the logs and the [commit](https://github.com/BuckleScript/bucklescript/commit/0f49d526dd0b40b8ec8f6eec03c011461d38c370) it was changed in

**Comment by hoichi** [comment]
> Interestingly, I don't see 8.1 mentioned in the changelog

Yet there’s [a blog post](https://reasonml.org/blog/bucklescript-8-1-new-syntax) and [a forum post](https://reasonml.chat/t/bucklescript-8-1-new-syntax-option/2379). Maybe Cheng felt that’s enough publicity :grinning:

**Comment by bobzhang** [comment]
8.1 is a dev release, the official release 8.2 should fix that

**Comment by DerivedMate** [comment]
> 8.1 is a dev release, the official release 8.2 should fix that

I've just checked that, and it's seem to be all fine, so I'll close the issue then
