### ISSUE TITLE
make a vscode action for "view fully ppxed source"

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#47]
It would work on the structure item level probably?
And it would trigger a hover thing, with [vscode.action.showHover](https://github.com/Microsoft/vscode/issues/32088#issuecomment-322154699) on the js side.
Not 100% sure how to send & handle custom messages though.

**Comment by naartjie** [comment]
Yes, this would greatly improve development with ppx methinks.

Is this a bit too tricky for a `good first issue`?

**Comment by anmonteiro** [comment]
I think this was done in https://github.com/jaredly/reason-language-server/commit/5aff8455ef64ff524d526d251c27368ed52f4f3e

Closing. Let's reopen if we're still not happy with it.
