### ISSUE TITLE
Support more recent OCaml versions (not just 4.02.3)

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#49]
Currently I can only handle projects that use 4.02.3.
This is fine for bucklescript/bsb-native, but for esy+jbuilder folks, it would be really nice to support 4.06 at least.

**Comment by chenglou** [comment]
Btw, see how I support multiple versions using a vendored omp here: https://github.com/chenglou/upgrade-reason-react

**Comment by thangngoc89** [comment]
@chenglou I think this is about Typed tree. OMP won't help much

**Comment by chenglou** [comment]
Crap, you're right.

**Comment by starper** [comment]
Support for at least `4.03` would be great. It's impossible to work with [graphql server](https://github.com/andreas/ocaml-graphql-server) without it.

**Comment by jaredly** [comment]
4.06.0 is now supported! I'll add in other versions if there's need
