### ISSUE TITLE
JSON RPC message id can be string

### ISSUE THREAD

**Issue by samskivert** [jaredly/reason-language-server#5]
The code currently assumes the JSON RPC message id will always be a number. The spec says it can be a string, a number or null (though then says "don't use null" so you probably don't have to worry about that case).

lsp4j uses string ids, which causes your server to think all messages are notifications because it fails to turn the string into a number. I hacked the code to just use Json.t as the id type, sending back whatever the client sent in the first place. This seems to work, though you may want a slightly less "expedient" solution. :)

**Comment by jaredly** [comment]
that seems fine to me :) feel free to send a pull-request!
