### ISSUE TITLE
Don't refmt a selection if it's just a part of a line

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#51]
Hi, not sure if thats intended but the extension adds a semicolon to whatever I paste in the editor. That might be helpful in a more context-sensitive way but right now it is a lot of work removing all those semicolons.

Here is a small example:
![semicolon_bug](https://user-images.githubusercontent.com/6476589/42408375-03b2cc22-81cc-11e8-8fc4-50b9bb1ac811.gif)

Version is the latest Beta 5!

**Comment by thangngoc89** [comment]
@jsiebern i disabled format on paste.

**Comment by jsiebern** [comment]
@thangngoc89 Thanks for the tip, it still shouldn't do that I believe :)

**Comment by thangngoc89** [comment]
@jaredly I’m thinking about removing semicolon if the input doesn’t have it, what do you think ?

**Comment by jaredly** [comment]
oh interesting :) I don't have any control over paste behavior, I just support formatting documents & selections via refmt

**Comment by jaredly** [comment]
so I guess I should check if you're formatting something that's within a single line, and maybe just bail?

**Comment by jsiebern** [comment]
I think that would make sense, I copy and paste a lot of stuff like variable names, and I’m sure  not alone! If it formats only the pasted code out of context, it would probably make a good compromise to look out for multi lines. The code will get formatted correctly on the next save anyway :)

**Comment by jaredly** [comment]
To fix this, check [here](https://github.com/jaredly/reason-language-server/blob/master/src/lsp/MessageHandlers.re#L336) whether both
a) `fst(start) == fst(end_)` (e.g. they're both on the same line), and
b) `text.[endPos] != '\n'` (it doesn't go to the end of the line)
If so, bail (return an empty list of edits).

**Comment by no-stack-dub-sack** [comment]
Seeing if I can figure this out...

**Comment by no-stack-dub-sack** [comment]
@jaredly Do you mean something like this, or am I interpreting this too literally?

```re
/*...*/
let substring = String.sub(text, startPos, endPos - startPos);

let isSingleLine = fst(start) == fst(end_) && text.[endPos] != '\n';

if (isSingleLine)  {
  /* return empty list of edits */
} else {
  /* continue calculating maybeResult */
}
```

**Comment by jaredly** [comment]
Yup, I think that should pretty much work! (module possible off-by-one etc.)

**Comment by no-stack-dub-sack** [comment]
@jaredly Sorry, can you clarify what you mean by module possible off-by-one etc.?

I think what I'm having trouble with is returning an empty list of edits. I understand maybe result is returning `Rpc.J.(...)` so I was going for: 
```re
if (isSingleLineEdit) {
  Rpc.J.(
    state,
    l([]),
  );
} else {
  /* ... */
}
```
figuring this is the empty list of edits it's looking for, but I keep getting 
```
  This is:
    (TopTypes.state * Json.t, string) Result.result (defined as
      (TopTypes.state * Json.t, string) Belt_Result.t)
  But somewhere wanted:
    TopTypes.state * Json.t
```
but not sure what `TopTypes.state * Json.t` is looking for. I'm perhaps not efficient enough at understanding these type errors yet, but it seems to have the same type signature that the function was originally expecting to return: `Result.result((TopTypes.state, Json.t), string)`
