### ISSUE TITLE
A type error causes unrelated bucklescript errors

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#55]
Hi, sorry for that bad title, not sure how to briefly describe this issue.

My issue is, that I have some `[@bs.as]` spread around my file. When I introduce a type error down later, it marks all those flags as `Unused BuckleScript attribute`, but fails to point out the "real" issue.

This is before the type error:
<img width="293" alt="bug1" src="https://user-images.githubusercontent.com/6476589/42495083-58246240-8422-11e8-8892-aad005655a9c.png">

This is where I introduced the error:
<img width="528" alt="bug3" src="https://user-images.githubusercontent.com/6476589/42495103-694ecdee-8422-11e8-82c2-bb63c84fbd53.png">

This is what `bsb` has to say about it:
<img width="550" alt="bug4" src="https://user-images.githubusercontent.com/6476589/42495114-7203c796-8422-11e8-9ce9-5f5077854305.png">

This is the error the LSP gives me:
<img width="283" alt="bug2" src="https://user-images.githubusercontent.com/6476589/42495120-7891568c-8422-11e8-8f40-a72033377788.png">

Message:
```
Warning 101: Unused BuckleScript attribute: bs.as
File "", line 55, characters 6-11:
Warning 101: Unused BuckleScript attribute: bs.as
File "", line 57, characters 6-17:
Warning 101: Unused BuckleScript attribute: bs.optional
File "", line 148, characters 58-67:
Error: This expression has type rule list
       but an expression was expected of type string
```

Here is the `debug.log` file if it helps at all:
[debug.log](https://github.com/jaredly/reason-language-server/files/2179245/debug.log)

**Comment by jaredly** [comment]
Ah yes, this is a failure in the error message parsing -- I should be reporting those warnings separately, and then the type error at line 148

**Comment by jaredly** [comment]
tracking as #65

**Comment by jaredly** [comment]
although the bucklescript messages are weird too

**Comment by jaredly** [comment]
Ok, I think those are fixed now too
