### ISSUE TITLE
Debug output hints at some potentially harcoded paths

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#56]
Hi, another thing I just noticed is that the debug output has a few hardcoded paths that might cause errors (or maybe not, I'm not sure if its an issue at all):

```
[Error - 10:17:01] Request textDocument/documentSymbol failed.
  Message: Not_foundRaised at file "hashtbl.ml", line 140, characters 23-32
Called from file "/Users/jared/clone/tools/reason-language-server/src/lsp/MessageHandlers.re", line 291, characters 52-79
Called from file "list.ml", line 55, characters 20-23
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "/Users/jared/clone/tools/reason-language-server/src/util/Infix.re", line 17, characters 68-73
Called from file "/Users/jared/clone/tools/reason-language-server/src/lsp/MessageHandlers.re", line 287, characters 18-1023
Called from file "/Users/jared/clone/tools/reason-language-server/src/lsp/BasicServer.re", line 38, characters 24-48
```

I don't have a user `jared` on my system, I checked 😅

**Comment by jaredly** [comment]
That's the debug symbols that are included for traceback reporting 😀 it doesn't impact runtime at all.
Thanks for checking though!
Also I should figure out that crash 🤔

**Comment by jsiebern** [comment]
I'm getting a lot of those crashes and it always focuses the output window, that's a little annoying as I have to switch back to the issues / terminal by hand each time 😅

**Comment by jaredly** [comment]
totally, I feel you -- this PR fixed it, but I think I reverted it by accident https://github.com/jaredly/reason-language-server/pull/40
