### ISSUE TITLE
Included modules don't show up in autocompletion

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#57]
I didn't find this in the issues anywhere, when i use the `include` statement inside of a module, I don't get any autocompletion for the imported types / lets, just the ones defined directly in the "child" module.

<img width="885" alt="include_module" src="https://user-images.githubusercontent.com/6476589/42514968-e72434d8-845a-11e8-9fa8-66e4a94f9ad9.png">

**Comment by jaredly** [comment]
Could you verify that this is fixed in the new release?

**Comment by jsiebern** [comment]
Hm, the latest release does not work at all for me unfortunately! I uninstalled beta 4 and installed beta 6 and it does nothing. When I manually try to trigger `Restart Reason Language Server`, it shows this:

<img width="1099" alt="test_re_ _bs-hapi-mongo-graphql-tests_und_visual_studio_code_display_language__locale_" src="https://user-images.githubusercontent.com/6476589/43079733-33949ab4-8e8e-11e8-9c4d-3c1633852dd1.png">

Otherwise - no autocomplete, codeglance, no nothing :(

**Comment by thangngoc89** [comment]
@jsiebern related to #62

**Comment by jaredly** [comment]
ok, fixed the new release

**Comment by jsiebern** [comment]
@jaredly I can confirm that include autocompletion works fine in `beta 6`!
