### ISSUE TITLE
It stops working on beta 6

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#62]
I just downloaded beta 6 version from the release page and it just stop working. No ideas why. 

Here is the log file
https://gist.github.com/thangngoc89/dd43e834c029033ee345178de779757a

**Comment by rej156** [comment]
+1 even built from source
beta 5 from source works though

**Comment by jaredly** [comment]
oops, I had a syntax error in the javascript file :P try again?

**Comment by thangngoc89** [comment]
@jaredly I re-dowloaded the vsix file from release page and try again. it doesn't even have a log. Should I build from source?

**Comment by jaredly** [comment]
hrmmm try turning the setting `reason_language_server.show_debug_errors` to true?

**Comment by thangngoc89** [comment]
@jaredly I tried it. No log file. But the output panel shows this:

```
[Error - 4:00:31 AM] Starting client failed
Error: spawn EACCES
	at exports._errnoException (util.js:1050:11)
	at ChildProcess.spawn (internal/child_process.js:319:11)
	at Object.exports.spawn (child_process.js:390:9)
	at _getServerWorkingDir.then.serverWorkingDir (/home/khoa/.vscode/extensions/jaredly.reason-vscode-1.0.0-beta.6/node_modules/vscode-languageclient/lib/main.js:346:40)
	at <anonymous>
```

**Comment by jaredly** [comment]
Huh, looks like maybe the linux binary doesn't have execute permissions? That's strange.

**Comment by thangngoc89** [comment]
@jaredly yep. that's exactly it. linux binary doesn't have execute permissions

**Comment by jaredly** [comment]
ok, uploaded a new .vsix

**Comment by jsiebern** [comment]
<img width="555" alt="dashboard_layout_re_ _dashboard" src="https://user-images.githubusercontent.com/6476589/43121123-f27eb890-8f1c-11e8-9645-cd80307da1f7.png">


Gettting this now, no output and no log file!

**Comment by rej156** [comment]
+1
```  Code: -32603 
Fatal error: exception Failure("Failed to refmt \"/Users/rej156/Documents/kauri-frontend/packages/kauri-web/node_modules/bs-platform/lib/refmt.exe\" --print binary --recoverable --parse re > \"/Users/rej156/Documents/kauri-frontend/packages/kauri-web/node_modules/.lsp/SubmitForReview_Module.ast\"\n/bin/sh: /Users/rej156/Documents/kauri-frontend/packages/kauri-web/node_modules/.lsp/SubmitForReview_Module.ast: No such file or directory")```

**Comment by rej156** [comment]
Ah works now, had to open my nested monorepo package as a folder in VsCode

**Comment by jsiebern** [comment]
@rej156 Thanks, same here!
