### ISSUE TITLE
False alarm with [@bs.optional]

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#63]
I have this code:

```
[@bs.deriving abstract]
  type jsProps = {
    value: string,
    onChange: string => unit,
    [@bs.optional]
    firstLineNumber: int,
  };
```

The lsp warns at `[@bs.optional]` . Run a clean bsb in the terminal doesn't give me any warnings.

**Comment by jaredly** [comment]
huh, what warning does it show?

**Comment by thangngoc89** [comment]
@jaredly unused Bucklescript attribute: bs.optional
