### ISSUE TITLE
Error got supressed when having a warning before it 

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#65]
Very simple code to reproduce

```
let add = (~first, ~second) => first + second;
add(1, 2);
let b = 2 |> abc;
```

It gives an **error** at `add(1,2)` but the message include error from `abc` 

```
Warning 6: labels were omitted in the application of this function.
File "", line 3, characters 13-16:
Error: Unbound value abc
Hint: Did you mean abs?
```

**Comment by jaredly** [comment]
Here's what needs to change: https://github.com/jaredly/reason-language-server/blob/master/src/lsp/Main.re#L164
The `Success()` branch allows for multiple warnings, but the `TypeError()` branch only expects a single thing -- I don't think it should be too complex

**Comment by thangngoc89** [comment]
@jaredly Does the message comes from `bsb` ? If that's true, why don't we split the message first?

**Comment by jaredly** [comment]
We could 🤷‍♂️  `message` is just the stdout from bsb

**Comment by ThierryCols** [comment]
Hey @jaredly, I'd like to have a look at it!

**Comment by jaredly** [comment]
Awesome, thanks! Let me know if you get stuck

**Comment by ThierryCols** [comment]
Hey @jaredly sorry for not updating you. 😭 

I think I'll parse the warning to separate it from the error. I'll send the PR asap, but there maybe another (larger) issue (ah ah suspense). I'll keep you posted!

**Comment by jaredly** [comment]
Ok I got impatient and fixed it 😅

**Comment by ThierryCols** [comment]
sorry for letting you down @jaredly 😥
