### ISSUE TITLE
"Missing dependency in search path" when compiling to es6 modules

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#68]
I have a module where I globally open `Css` from the `bs-css` package. The `beta 6` shows an error like so:

<img width="564" alt="dashboard_layout_re_ _frontend" src="https://user-images.githubusercontent.com/6476589/43194707-56a90b72-9003-11e8-8118-75c890c240e9.png">

```
File "", line 1:
Error: Missing dependency Css in search path
```

When I use a local open, it works fine, no errors:
<img width="477" alt="dashboard_layout_re_ _frontend2" src="https://user-images.githubusercontent.com/6476589/43194727-67167c60-9003-11e8-9c4b-c818f476efb0.png">

`debug.log`:
[debug.log](https://github.com/jaredly/reason-language-server/files/2227499/debug.log)

**Comment by jsiebern** [comment]
Hm, now it shows missing dependency for "ReasonReact" in another file, not sure whats going on as it autocompletes those "missing" dependencies without issues.

**Comment by jsiebern** [comment]
And the error vanishes if another is present. It returns once it is the only one again.

**Comment by jsiebern** [comment]
Now this is an interesting error for this issue I think:

```
/bin/sh: /path/Dashboard/frontend/node_modules/bs-css/node_modules/.bin/bsb: No such file or directory
```

It looks like it searches for `bsb` inside the `bs-css` node module, not sure what to make of that!

[debug.log](https://github.com/jaredly/reason-language-server/files/2227664/debug.log)

**Comment by jaredly** [comment]
Hmmm. So the compilation line in debug.log shows:

```
/path//Dashboard/frontend/node_modules/bs-platform/lib/bsc.exe -I "/path//Dashboard/frontend/node_modules/.lsp" -I "/path//Dashboard/frontend/node_modules/bs-platform/lib/ocaml" -I "/path//Dashboard/frontend/node_modules/bs-platform/lib/ocaml" -I "/path//Dashboard/frontend/node_modules/@digitalsolutions/flytools.reason-components/lib/bs/src" -I "/path//Dashboard/frontend/node_modules/bs-react-intl/lib/bs/src" -I "/path//Dashboard/frontend/node_modules/bs-css/lib/bs/src" -I "/path//Dashboard/frontend/node_modules/reason-apollo/lib/bs/src" -I "/path//Dashboard/frontend/node_modules/reason-apollo/lib/bs/src/graphql-types" -I "/path//Dashboard/frontend/node_modules/reason-react/lib/bs/src" -I "/path//Dashboard/frontend/node_modules/@jsiebern/bs-material-ui/lib/bs/src" -I "/path//Dashboard/frontend/lib/bs/src" -I "/path//Dashboard/frontend/lib/bs/src/Reason" -I "/path//Dashboard/frontend/lib/bs/src/Reason/Components" -I "/path//Dashboard/frontend/lib/bs/src/translations" -bin-annot -ppx /path//Dashboard/frontend/node_modules/graphql_ppx/ppx -ppx '/path//Dashboard/frontend/node_modules/bs-platform/lib/reactjs_jsx_ppx_2.exe' -ppx /path//Dashboard/frontend/node_modules/bs-platform/lib/bsppx.exe -nostdlib -no-alias-deps -color always -w -30-40+6+7+27+32..39+44+45+101 -impl /path//Dashboard/frontend/node_modules/.lsp/Dashboard_Layout.ast
```

Which does show that `bs-css` is included. And that error you're seeing is directly copied from the `bsc` output. Which makes it confusing that you're getting inconsistent results :/ could you try to make a minimal repro case?

**Comment by jsiebern** [comment]
Sure, this was easier to reproduce than I thought!

https://github.com/jsiebern/lsp-repro

Produces the error
```
File "", line 1:
Error: Missing dependency ReasonReact in search path
```

right away, though `bsb` compiles fine!

[debug.log](https://github.com/jaredly/reason-language-server/files/2237733/debug.log)

**Comment by jaredly** [comment]
Ah, looks like it's a breaking change in bucklescript 4.0 :/ there's nothing listed in the changelog, so I'll have to dig around to figure out what's going on.

**Comment by jaredly** [comment]
orrr nope. It's there in 3.x

**Comment by jaredly** [comment]
ah ok, I figured out the issue. If you change the module type to `commonjs`, then the error disappears. Not sure why...
I think the error is being produced [here](https://github.com/BuckleScript/bucklescript/blob/40153e75a6470047cdc88d02885e69c22a6bbe70/jscomp/core/js_packages_info.ml#L222).

**Comment by jsiebern** [comment]
That’s odd, I’ve tried all bsconfig options and deleted the .lsp folder after each change! I’ll  try again!

**Comment by jsiebern** [comment]
Confirmed, thank you!

**Comment by thangngoc89** [comment]
this is awesome. 🔥
