### ISSUE TITLE
Autocomplete doesn't dedup between things overridden in `open`s

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#70]
e.g.
```
module A = { let x = 3 };
module B = { let x = "hi"; };
open A;
open B;
x<cursor>
```
will autocomplete *both* x as an `int` and x as a `string`, when x as a `string` is the only one that should be shown.

see also #44

**Comment by jaredly** [comment]
Fixing this will require changing [this `Belt.List.map`](https://github.com/jaredly/reason-language-server/blob/master/src/analyze/NewCompletions.re#L343) to a `Belt.List.reduce`, keeping a `Hashtbl` of already used identifiers, to dedup.

**Comment by abs-zero** [comment]
I'd like to take this.

**Comment by jaredly** [comment]
Thanks!

**Comment by abs-zero** [comment]
I have a few questions:
1. Why use Hashtbl instead of Hashmap?
2. How do I get used identifiers?
3. Since hashtbl api is mutable and side-effecty, wouldn't it be better to use `forEach` instead of `reduce`?

**Comment by jaredly** [comment]
btw thanks for jumping in to help!

**Comment by abs-zero** [comment]
Thanks for explaining. I tried your implementation and I got one `x` of `string` and two `x` of `int`. Is this expected that to show `x`s of local completions too? 

![2018-07-30-214919_487x242_scrot](https://user-images.githubusercontent.com/16974688/43409035-7f2b7538-9442-11e8-9620-10285909749f.png)
![2018-07-30-215202_477x108_scrot](https://user-images.githubusercontent.com/16974688/43409123-d427ec6a-9442-11e8-99f2-e34176a6d995.png)

I assumed the first two was from local value completions. So, I tried returning only `two` (to ignore local value completions) and I got `x` of `int` only. Shouldn't this be `x` of `string`?

**Comment by jaredly** [comment]
Yeah, that's probably as far as we can get for now. it will take more work to determine that the other "x"s are out of scope

**Comment by abs-zero** [comment]
Should I make a PR then with that?

**Comment by jaredly** [comment]
Yes please!
