### ISSUE TITLE
Lsp is generating output in wrong folder and incorrect file extension

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#71]
I'm using the latest commit in master https://github.com/jaredly/reason-language-server/commit/9f269a2b3df4cf11010eaf395020b8db6238e602

My [repo](https://github.com/thangngoc89/rtop-ui/) has a fairly complicated setup:

```js
{
  "sources": [
    "src",
    "src/vendor",
    "src_editor",
    "src_analyzer",
    {
      "dir": "src_analyzer/__tests__",
      "type": "dev"
    }
  ],
  "suffix": ".bs.js",
}
```

When editing any files inside any folder, it generates artifact in `/src` with `.js` extension
Any ideas?

**Comment by jaredly** [comment]
hrmmm I don't think lsp should be generating `.js` files at all... you're sure that's where it's coming from?

**Comment by thangngoc89** [comment]
@jaredly yep. it comes from lsp. bsb -w doesn't generate anything

**Comment by thangngoc89** [comment]
@jaredly could you please provide some directions for me to debugging this thing? 

My src folder looks like this right now

![image](https://user-images.githubusercontent.com/3049054/43991166-096c7204-9d91-11e8-9018-abb8955b4391.png)

**Comment by jaredly** [comment]
Wow sorry about that 😅 what is your bsb version?

**Comment by thangngoc89** [comment]
bsb 4.0.3 
I'm on Ubuntu 18.04 if that's matter

**Comment by jaredly** [comment]
Ok, I grabbed your repo and I can repro. looking into it

**Comment by thangngoc89** [comment]
@jaredly thank you very much. Not sure what's going on. ¯\_(ツ)_/¯

**Comment by jaredly** [comment]
Ok, this should fix it https://github.com/jaredly/reason-language-server/commit/3b307eb8d0012ee2828ddafc7236292c6e8a7d67
lmk if it recurs!

**Comment by thangngoc89** [comment]
@jaredly Awesome. Let's me try this
