### ISSUE TITLE
%bs.raw seems to break module pathing

### ISSUE THREAD

**Issue by wegry** [jaredly/reason-language-server#72]
In a project that bsb@4.0.1 builds without warnings or errors, it seems like the LSP plugin is getting tripped up by ppx.

```
Cannot parse type error: File "", line 1:
Error: Missing dependency Icon-Demo in search path
Sending notification {"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file://.../src/Components/AppHeader.re", "diagnostics": [{"range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}, "message": "File \"\", line 1:\nError: Missing dependency Icon-Demo in search path", "severity": 1}]}}
```
In a module named Badge, I get the following error, but this crops up in all files that import scss at the top with bs.raw.

![screen shot 2018-07-29 at 2 40 19 pm](https://user-images.githubusercontent.com/5156873/43366377-6026ac76-933d-11e8-8b8d-8caebc4c706d.png)

**Comment by wegry** [comment]
@thangngoc89 Thanks for the quick response. As of 9f269a2, this issue still persists.

**Comment by jaredly** [comment]
ahhh interesting. So I removed the bucklescript ppx to get rid of "unused bucklescript attribute" errors, but now it looks like that's causing other problems. Could you try reverting https://github.com/jaredly/reason-language-server/commit/d49fc771c109c39bdb50c17be4b56e03e190d284 and see if that fixes it?

**Comment by wegry** [comment]
@jaredly ```diff
diff --git a/src/analyze/State.re b/src/analyze/State.re
index ba6fd57..04bc349 100644
--- a/src/analyze/State.re
+++ b/src/analyze/State.re
@@ -68,7 +68,7 @@ let newBsPackage = (rootPath) => {
         "-bs-package-output",
         "es6:src",
         ...flags] : flags;
-      ["-bs-no-builtin-ppx-ml", ...flags];
+      flags;
     }
     | _ => flags
   };
 ``` still produces the same error, unfortunately.

**Comment by jaredly** [comment]
Can you try with the latest master? I'm unable to repro now.

**Comment by wegry** [comment]
<img width="309" alt="screen shot 2018-08-21 at 08 10 49" src="https://user-images.githubusercontent.com/5156873/44383686-d3254280-a519-11e8-857e-6b067159fe4e.png">

Still looks like it's breaking (but on something else now with commit 33e26a6). I might try working around with it with something like 
```ocaml
let importCss = [%bs.raw a => {j|import '$a'|j}];
```

which doesn't get clobbered by the plugin.

**Comment by jaredly** [comment]
hmmm it seems to be working fine in my testing 🤔 
![image](https://user-images.githubusercontent.com/112170/44621646-bfa21080-a866-11e8-8560-7f8b59f0ec49.png)
turns into
![image](https://user-images.githubusercontent.com/112170/44621647-c9c40f00-a866-11e8-96d8-b0215e254d76.png)

**Comment by wegry** [comment]
I tried moving the import after an export declaration (like you example below). Still no dice. The differences I see are that my `%bs.raw` line is getting broken into two lines from the actual import.

![image](https://user-images.githubusercontent.com/5156873/44648531-9eb1fa80-a9e1-11e8-9ea8-ad7bdd9747b9.png)

Other than that, it may be a bug (with the plugin?) elsewhere in the file? It builds with the currently recommended VS Code extension. Code completion is why I was hoping to switch over to this plugin.

But even when I go to remove the css import, I still get the `Fatal error: exception Not_found`.

![image](https://user-images.githubusercontent.com/5156873/44648625-e59ff000-a9e1-11e8-9229-d1bbffa9c0e6.png)

**Comment by jaredly** [comment]
@wegry here's the project that I'm using to test https://github.com/jaredly/reason-language-server/blob/master/examples/example-es6-imports/src/Hello.re
Could you put up an example project that demonstrates the bug, or PR with a change to the `example-es6-imports` project that produces the bug?

**Comment by wegry** [comment]
I think as it stands, the ppx fix probably works (just not in my case). There's a bug affecting another language/project construct (maybe).

**Comment by wegry** [comment]
I'll try creating a minimal reproduction of the newer issue as well.
