### ISSUE TITLE
Support inference from .cmi files locally when .cmt's are absent

### ISSUE THREAD

**Issue by cristianoc** [jaredly/reason-language-server#76]
Delete the .cmt files, or just try a project that does not generate them.

**Comment by jaredly** [comment]
ooh good call :)

**Comment by jaredly** [comment]
Ok, this is working now

**Comment by cristianoc** [comment]
Nice!
Is the format of .cmi's pretty much the same as .cmt's, but with more info?

**Comment by jaredly** [comment]
Cmt's have more info, but yes. cmi's have a `TypedTree.signature`, whereas cmt's have a `TypedTree.structure` generally. Also cmt's have the ability to report partial type info (all the inferred types up until a type error, for example)
