### ISSUE TITLE
Latest bsb was not automatically detected

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#79]
Hi, please close this immediately if it is just my stupidity, but I came across an issue having updated both `bsb` and the language server to the latest version!

Meaning:
`reason-cli@3.3.2-macos-1`
`bs-platform@4.0.3`
`reason-vscode-1.0.0-beta.6-1-2.vsix`

The language server wasn't able to detect / use the `bsbrefmt` on its own as it used to do before, it threw an error that it could not execute `refmt`. I went ahead and set the config option

`"reason_language_server.refmt": "./node_modules/bs-platform/lib/bsrefmt"`

and it worked fine again. It's not super important as it works fine with setting the option but still wanted to report it :)

**Comment by jaredly** [comment]
ooh, thanks for reporting!

**Comment by jaredly** [comment]
published https://github.com/jaredly/reason-language-server/releases/tag/1.0.0-beta.6-2
