### ISSUE TITLE
Doesn't find dune files

### ISSUE THREAD

**Issue by zploskey** [jaredly/reason-language-server#81]
On a native project that builds with dune the language server reports that it is unable to find a jbuild file. We should probably be looking for dune files first, falling back to jbuild files, then failing.

**Comment by jaredly** [comment]
Thanks! When you do that, could you add a dune example to the `examples` directory? So that it will be easy to verify in the future that everything works

**Comment by zploskey** [comment]
I guess an Esy project won't fit with the contributing instructions that say to install with npm in a loop. How do you feel about that? We could just write a quick script do the setup, too, I guess.

**Comment by jaredly** [comment]
Yeah, if you could reproduce something similar that would be great. I'll remove that line from the contributing instructions -- it's not really needed anymore.
