### ISSUE TITLE
Doesn't seem to work when project not compiled to native

### ISSUE THREAD

**Issue by bsansouci** [jaredly/reason-language-server#84]
I can't get this to work when I compile to bytecode or js.

**Comment by jaredly** [comment]
hrmmm yeah I need a way to specify which target you want to be using. Currently I think I just take the compilation mode of the first entry in your `entries` list

**Comment by jaredly** [comment]
that's an interesting idea! It doesn't look there's any information in the .merlin that directly indicates what mode is being used, but I could infer it from the paths of things

**Comment by bsansouci** [comment]
By "what mode" do you mean what backend to pass to `-backend`?

**Comment by bsansouci** [comment]
Could we add a comment to .merlin that we parse from reason-language-server?

**Comment by jaredly** [comment]
Yup https://github.com/jaredly/reason-language-server/blob/master/src/analyze/State.re#L121

**Comment by jaredly** [comment]
Umm why not a workspace-local vscode setting?

**Comment by bsansouci** [comment]
Well because my project might change compile target at any time and I don't want to update a config file

**Comment by jaredly** [comment]
Sooo I changed the plugin recently to run `bsb` for you whenever you save a file, so I think things should mostly work? e.g. you could be compiling to js, but if you're editing stuff that's touched by native entries, then it will still work, because rls will be running `bsb -make-world -backend native` behind the scenes.

**Comment by bsansouci** [comment]
Mmmh so you could compare the path of the current file with the `sources` field inside the bsconfig and figure out if it's only compiled to one target. If it can be compiled to multiple targets it might get a little tricky, because the vendored ocaml supports `#if BSB_BACKEND` so if we compile to JS say, and there's a compile time check for native, then we won't report any errors there. I'm not sure how to best handle that... Maybe call the compiler twice?
