### ISSUE TITLE
Code Helper for ExtensionHost goes to 100% CPU when clicking on specific code

### ISSUE THREAD

**Issue by tmepple** [jaredly/reason-language-server#85]
Latest built `master` version on MacOS 10.13.6 w/latest VSCode, latest bs-platform 4.0.5.

When working in my project (only on certain modules/.re files) I noticed Code Helper.app (for ExtensionHost) occasionally would crash and go to 100% CPU.  The only way out was to run `kill` against the errant processes.

I was able to isolate the issue so it consistently happens by clicking on a specific line of code.  I copied one of my .re files into the https://github.com/tmepple/my-react-app project I setup yesterday when troubleshooting another issue to provide the reproduction.  I was going to add all of the dependencies (i.e. reason-apollo, re-formality, etc) to `package.json` and `bsconfig.json` but I found that wasn't even necessary to get this specific issue to happen.

To peg the CPU at 100% every time I open the project in VSCode (after getting deps with `yarn`), open the `SignupForm.re` file in /src/components and click on the text `preventDefault` on line 170 (whole line is `id="signup_form" onSubmit={form.submit |> Formality.Dom.preventDefault}>`).

[debug.log](https://github.com/jaredly/reason-language-server/files/2291447/debug.log)

**Comment by tmepple** [comment]
Ouch!  Glad you found that and thanks for looking at it so fast.  Apologies I can only push issues and not PRs at this point in this language.  Thanks for your regular huge contributions to the community through important projects such as this!

**Comment by jaredly** [comment]
No problem :) unfortunately I can't actually repro -- the my-react-app repo didn't produce the bug for me. Could you try to reduce the size of the SignupForm.re to see what the minimal repro case is for you?

**Comment by tmepple** [comment]
Hmmmm... yeah interesting.  Not sure what about my global environment would make it not able to be reproduced.  Ok I will try to make it a more minimal repro in a few hours.

**Comment by tmepple** [comment]
After disabling every extension except for this one, I can no longer repro.  Seems like another extension or VSC itself is hanging.  Thanks for taking a look... Closing at this point.
