### ISSUE TITLE
Distinguish normal compilation output from bsb error reports.

### ISSUE THREAD

**Issue by cristianoc** [jaredly/reason-language-server#88]
genFlow currently prints some extra messages as part of compilation output, for example:
```
  Add src/ReasonReact.cmti  src/ReasonReact.mliast
```
this is picked up by the vscode extension and reported as an error with no location (at the beginning of the file).

**Comment by jaredly** [comment]
hmmmm unfortunately bsb outputs error messages to stdout :( so there's probably not a clean way to do this

**Comment by cristianoc** [comment]
Looks like stderr is picked up the same way by the error reporter.

**Comment by jaredly** [comment]
Yeah, because dune's errors go to stderr 🙃

**Comment by jaredly** [comment]
errr wait, actually I was confusing two different outputs. This should actually be solvable.

**Comment by jaredly** [comment]
@cristianoc  Could you make an entry in the `examples` repo with genflow set up? So that I can test against it.

**Comment by cristianoc** [comment]
@jaredly sure https://github.com/jaredly/reason-language-server/pull/120.

**Comment by cristianoc** [comment]
Closing as now genFlow uses a separate log file.
