### ISSUE TITLE
Some bsc-flags from bsconfig is not being respected

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#89]
In `bsconfig.json` I have `bsc-flags` property set to this value:

```
"bsc-flags": ["-bs-super-errors", "-w -45", "-open Belt"],
```

But warning `45` still shows up in diagnostic panel.

**Comment by jaredly** [comment]
The solution for this is to use the `"warnings"` field for warnings. bucklescript doesn't generate the right .merlin file in this instance
