### ISSUE TITLE
Variant autocompletion

### ISSUE THREAD

**Issue by IwanKaramazow** [jaredly/reason-language-server#94]
![image](https://user-images.githubusercontent.com/10634678/44296993-79c6d480-a2c9-11e8-91d5-f9120d93a4f4.png)

Variants do not autocomplete when typing a `.` after a module.
Not sure to what extend this is possible, but I expected to see `NoUpdate`, `SideEffects` etc.
appear in the `ReasonReact` autocompletion list.

**Comment by jaredly** [comment]
Ok this is fixed
