### ISSUE TITLE
Language server generating huge debug.log (seems to restart all the time)

### ISSUE THREAD

**Issue by jsiebern** [jaredly/reason-language-server#95]
Hi, I can't say for sure what seems to cause this, but in my experiment after I realized what was going on I just opened **one** reason file. The debug file became huge after a while (several hundred megabytes) with me changing anything.

I'll attach a debug file captured after a restart and a quick exit of VSCode (so only 1mb). I realized something was off when I hovered over a type and when I scrolled the definition it jumped to the top every few hundred milliseconds on its own.

The only thing I could think of that caused this is the installation of a new package maybe? I'll actually try a clean `node_modules` now, still want you to know this happened though, I'll report back on that try.

[debug.log](https://github.com/jaredly/reason-language-server/files/2299577/debug.log)

**Comment by jsiebern** [comment]
Nope, still doing it after a clean re-install of everything!

**Comment by jsiebern** [comment]
One more note: This causes my Webpack to go haywire btw, recompiling every second and running out of memory eventually.

**Comment by thangngoc89** [comment]
@jsiebern did you accidentally enable debug mode? because it doesn't generate debug logs by default

**Comment by jsiebern** [comment]
@thangngoc89 Looks like I did, disabled it, restarted, same problem just with a slower file growth (missing debug output probably)

**Comment by jaredly** [comment]
Ok, I just fixed a bug where rls was restarting a ton (#100) - maybe now it'll be better?

**Comment by jsiebern** [comment]
Thank you, release 1.0.0 fixed it!
