### ISSUE TITLE
rls doesn't show type info for whitespace, symbols, as much as merlin does

### ISSUE THREAD

**Issue by cristianoc** [jaredly/reason-language-server#97]
The comments below show the type information for each character, in the case of the two vscode extensions.
Things to notice:
- how `x` and `y:0` are treated differently
- reason-vscode does not show type information for `0`
- OCaml and Reason IDE shows `int` for `}` and `point` for `;`

```reason
type point = {
  x: int,
  y: int,
};

let foo = x => {x, y: 0};
/*        iiaaapiippppiip   OCaml and Reason IDE */
/*        ii    ii pp       reason-vscode */

/*        i: int 
          p: point
          a: int => point */
```

**Comment by jaredly** [comment]
Does whitespace have type information? Should symbols trigger type hover?
I've been going with the assumption that it only makes sense to generate hover info for identifiers, but I'm open to changing that.

**Comment by cristianoc** [comment]
Only for identifiers sounds the cleanest.
So in this case the questions are:
- treating x and y the same
- giving int on 0

**Comment by jaredly** [comment]
- it looks like both x & y are picking up the symbol to the right of it, not sure why that is
- Yeah, I don't treat string & number constants as identifiers, but I'd be fine to add that in

**Comment by cristianoc** [comment]
I suspect some of this is due to the parser.

**Comment by cristianoc** [comment]
+ @piesync

**Comment by cristianoc** [comment]
+ @IwanKaramazow

**Comment by cristianoc** [comment]
@chenglou you went trough some of these symbol position + 1 issues if I remember.

**Comment by chenglou** [comment]
Not sure if related, but yeah. https://github.com/BuckleScript/bucklescript/blob/master/jscomp/super_errors/super_location.ml and https://github.com/BuckleScript/bucklescript/blob/master/jscomp/super_errors/super_misc.ml

**Comment by cristianoc** [comment]
Just thought why you'd want type info for numbers: to help with the initial confusion that `1` has a different type than `1.0
