### ISSUE TITLE
Formatting perf regression

### ISSUE THREAD

**Issue by alexfedoseev** [jaredly/reason-language-server#99]
I noticed perf regression (relative to `ocaml-language-server`) when formatting on save is invoked.

The avg numbers in Atom editor:

```
OSL: 55–65ms
RSL: 300–320ms
```

Here's log entries:

```shell
# OSL
Reason (reason) rpc.sendRequest textDocument/formatting sending 
Reason (reason) rpc.sendRequest textDocument/formatting received (64ms) 

# RSL
Reason (reason) rpc.sendRequest textDocument/rangeFormatting sending
Reason (reason) rpc.sendRequest textDocument/rangeFormatting received (310ms)
```

**Comment by jaredly** [comment]
I wonder why format-on-save is invoking the rangeFormatting function instead of the `textDocument/formatting` event (I know OSL doesn't support range formatting...)

**Comment by thangngoc89** [comment]
Oh yeah. rangeFormatting does a lot of stuff. formatting should be faster

**Comment by alexfedoseev** [comment]
Looks like b/c RLS supports it: https://github.com/atom/atom-languageclient/blob/0f6bb78d2081e49f1e1a9a5e70b4c6eee89196c1/lib/adapters/code-format-adapter.ts#L49-L51

**Comment by alexfedoseev** [comment]
Language client prolly should check if action is triggered via keybinding _and_ if selection length in active buffer is > 0 (not sure how hard is it tho). Doing this on save doesn't make a lot of sense especially if it's so much slower.

**Comment by jaredly** [comment]
The language server protocol doesn't expose any of that information 😒 
put we could do a "if the range is the whole document, just do a straight refmt"

**Comment by alexfedoseev** [comment]
I meant that `format` function from atom language client code (the one that’s linked) should make these checks before sending request to language server. I wonder how it’s done in vscode’s language client.

**Comment by thangngoc89** [comment]
@alexfedoseev In VSCode, there are different command for rangeFormatting and codeFormatting

**Comment by jaredly** [comment]
Oh totally, would be great for the atom client to do that better

**Comment by thangngoc89** [comment]
@jaredly I can help with detecting whole file selection in rangeFormatting (I'm basically write the whole function :P)

**Comment by alexfedoseev** [comment]
@thangngoc89 atom also has two functions, just its detection of when invoke what is pretty dumb: if language server supports range formatting then send rangeFormatting event. I prolly should create an issue there to discuss this behavior, it’s better to fix it there thus other languages can benefit from it.

**Comment by alexfedoseev** [comment]
@jaredly I submitted PR to `atom-languageclient` (https://github.com/atom/atom-languageclient/pull/231) and testing it right now.

It kinda works but timing is still bad and there is one more issue: after I hit save a file is formatted but cursor jumps to the end of the file. And I'm not sure if this is me messed up w/ something in PR or the issue is on RLS side.

I checked OLS and it works fine. Here is the diff in the logs that I noticed:

1. In OLS: `textDocument/formatting received: []` (empty array)
2. In OLS: `textDocument/didChange` contains **only** changes + range (screen: https://cl.ly/173c2O220C0o)

In RLS there's a full file contents in payload in both cases.

**Comment by alexfedoseev** [comment]
@thangngoc89 It shouldn't be hard to maintain cursor position but it looks like OLS optimized this part very well:
1. It doesn't pass around the whole buffer (maybe this is one of the reasons why it's significantly faster?)
2. And as a nice side effect, cursor position is maintained w/o additional moves on a client

**Comment by alexfedoseev** [comment]
After some voodoo w/ services & bump RLS to `1.0.0` (I assume infinite loop invested in this perf regression a lot) OLS & RLS formatting perf is on the same level.

Fix will be available in the next atom plugin release. Closing this.
